/* named_array_blobs.h — GENERATED by tools/gen_named_array_blobs.py
 * 13 个以 _N_M_ 成员访问的数组全局的精确尺寸覆盖结构 + 指针 cast 宏。
 * 尺寸证据：collect_array_spec.py（globals.h 声明 + 函数文件实际访问）。
 * 原 extern unsigned char NAME[N] 保持不变 → 零 ABI 变化；成员访问经 NAME_blob 宏。
 * 每个 4 对齐窗口同时提供 _w_1_ 字节与 _w_4_ 字（覆盖 M∈{1,4}，4 字节全 4 对齐）。*/
#ifndef RK_NAMED_ARRAY_BLOBS_H
#define RK_NAMED_ARRAY_BLOBS_H

typedef union {
    unsigned char raw[220];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
        union { struct { unsigned char _72_1_, _73_1_, _74_1_, _75_1_; }; unsigned int _72_4_; };
        union { struct { unsigned char _76_1_, _77_1_, _78_1_, _79_1_; }; unsigned int _76_4_; };
        union { struct { unsigned char _80_1_, _81_1_, _82_1_, _83_1_; }; unsigned int _80_4_; };
        union { struct { unsigned char _84_1_, _85_1_, _86_1_, _87_1_; }; unsigned int _84_4_; };
        union { struct { unsigned char _88_1_, _89_1_, _90_1_, _91_1_; }; unsigned int _88_4_; };
        union { struct { unsigned char _92_1_, _93_1_, _94_1_, _95_1_; }; unsigned int _92_4_; };
        union { struct { unsigned char _96_1_, _97_1_, _98_1_, _99_1_; }; unsigned int _96_4_; };
        union { struct { unsigned char _100_1_, _101_1_, _102_1_, _103_1_; }; unsigned int _100_4_; };
        union { struct { unsigned char _104_1_, _105_1_, _106_1_, _107_1_; }; unsigned int _104_4_; };
        union { struct { unsigned char _108_1_, _109_1_, _110_1_, _111_1_; }; unsigned int _108_4_; };
        union { struct { unsigned char _112_1_, _113_1_, _114_1_, _115_1_; }; unsigned int _112_4_; };
        union { struct { unsigned char _116_1_, _117_1_, _118_1_, _119_1_; }; unsigned int _116_4_; };
        union { struct { unsigned char _120_1_, _121_1_, _122_1_, _123_1_; }; unsigned int _120_4_; };
        union { struct { unsigned char _124_1_, _125_1_, _126_1_, _127_1_; }; unsigned int _124_4_; };
        union { struct { unsigned char _128_1_, _129_1_, _130_1_, _131_1_; }; unsigned int _128_4_; };
        union { struct { unsigned char _132_1_, _133_1_, _134_1_, _135_1_; }; unsigned int _132_4_; };
        union { struct { unsigned char _136_1_, _137_1_, _138_1_, _139_1_; }; unsigned int _136_4_; };
        union { struct { unsigned char _140_1_, _141_1_, _142_1_, _143_1_; }; unsigned int _140_4_; };
        union { struct { unsigned char _144_1_, _145_1_, _146_1_, _147_1_; }; unsigned int _144_4_; };
        union { struct { unsigned char _148_1_, _149_1_, _150_1_, _151_1_; }; unsigned int _148_4_; };
        union { struct { unsigned char _152_1_, _153_1_, _154_1_, _155_1_; }; unsigned int _152_4_; };
        union { struct { unsigned char _156_1_, _157_1_, _158_1_, _159_1_; }; unsigned int _156_4_; };
        union { struct { unsigned char _160_1_, _161_1_, _162_1_, _163_1_; }; unsigned int _160_4_; };
        union { struct { unsigned char _164_1_, _165_1_, _166_1_, _167_1_; }; unsigned int _164_4_; };
        union { struct { unsigned char _168_1_, _169_1_, _170_1_, _171_1_; }; unsigned int _168_4_; };
        union { struct { unsigned char _172_1_, _173_1_, _174_1_, _175_1_; }; unsigned int _172_4_; };
        union { struct { unsigned char _176_1_, _177_1_, _178_1_, _179_1_; }; unsigned int _176_4_; };
        union { struct { unsigned char _180_1_, _181_1_, _182_1_, _183_1_; }; unsigned int _180_4_; };
        union { struct { unsigned char _184_1_, _185_1_, _186_1_, _187_1_; }; unsigned int _184_4_; };
        union { struct { unsigned char _188_1_, _189_1_, _190_1_, _191_1_; }; unsigned int _188_4_; };
        union { struct { unsigned char _192_1_, _193_1_, _194_1_, _195_1_; }; unsigned int _192_4_; };
        union { struct { unsigned char _196_1_, _197_1_, _198_1_, _199_1_; }; unsigned int _196_4_; };
        union { struct { unsigned char _200_1_, _201_1_, _202_1_, _203_1_; }; unsigned int _200_4_; };
        union { struct { unsigned char _204_1_, _205_1_, _206_1_, _207_1_; }; unsigned int _204_4_; };
        union { struct { unsigned char _208_1_, _209_1_, _210_1_, _211_1_; }; unsigned int _208_4_; };
        union { struct { unsigned char _212_1_, _213_1_, _214_1_, _215_1_; }; unsigned int _212_4_; };
        union { struct { unsigned char _216_1_, _217_1_, _218_1_, _219_1_; }; unsigned int _216_4_; };
    };
} P1_Table_t;
#define P1_Table_blob (*(P1_Table_t*)&P1_Table)

typedef union {
    unsigned char raw[32];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
    };
} fontname_t;
#define fontname_blob (*(fontname_t*)&fontname)

typedef union {
    unsigned char raw[924];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
        union { struct { unsigned char _72_1_, _73_1_, _74_1_, _75_1_; }; unsigned int _72_4_; };
        union { struct { unsigned char _76_1_, _77_1_, _78_1_, _79_1_; }; unsigned int _76_4_; };
        union { struct { unsigned char _80_1_, _81_1_, _82_1_, _83_1_; }; unsigned int _80_4_; };
        union { struct { unsigned char _84_1_, _85_1_, _86_1_, _87_1_; }; unsigned int _84_4_; };
        union { struct { unsigned char _88_1_, _89_1_, _90_1_, _91_1_; }; unsigned int _88_4_; };
        union { struct { unsigned char _92_1_, _93_1_, _94_1_, _95_1_; }; unsigned int _92_4_; };
        union { struct { unsigned char _96_1_, _97_1_, _98_1_, _99_1_; }; unsigned int _96_4_; };
        union { struct { unsigned char _100_1_, _101_1_, _102_1_, _103_1_; }; unsigned int _100_4_; };
        union { struct { unsigned char _104_1_, _105_1_, _106_1_, _107_1_; }; unsigned int _104_4_; };
        union { struct { unsigned char _108_1_, _109_1_, _110_1_, _111_1_; }; unsigned int _108_4_; };
        union { struct { unsigned char _112_1_, _113_1_, _114_1_, _115_1_; }; unsigned int _112_4_; };
        union { struct { unsigned char _116_1_, _117_1_, _118_1_, _119_1_; }; unsigned int _116_4_; };
        union { struct { unsigned char _120_1_, _121_1_, _122_1_, _123_1_; }; unsigned int _120_4_; };
        union { struct { unsigned char _124_1_, _125_1_, _126_1_, _127_1_; }; unsigned int _124_4_; };
        union { struct { unsigned char _128_1_, _129_1_, _130_1_, _131_1_; }; unsigned int _128_4_; };
        union { struct { unsigned char _132_1_, _133_1_, _134_1_, _135_1_; }; unsigned int _132_4_; };
        union { struct { unsigned char _136_1_, _137_1_, _138_1_, _139_1_; }; unsigned int _136_4_; };
        union { struct { unsigned char _140_1_, _141_1_, _142_1_, _143_1_; }; unsigned int _140_4_; };
        union { struct { unsigned char _144_1_, _145_1_, _146_1_, _147_1_; }; unsigned int _144_4_; };
        union { struct { unsigned char _148_1_, _149_1_, _150_1_, _151_1_; }; unsigned int _148_4_; };
        union { struct { unsigned char _152_1_, _153_1_, _154_1_, _155_1_; }; unsigned int _152_4_; };
        union { struct { unsigned char _156_1_, _157_1_, _158_1_, _159_1_; }; unsigned int _156_4_; };
        union { struct { unsigned char _160_1_, _161_1_, _162_1_, _163_1_; }; unsigned int _160_4_; };
        union { struct { unsigned char _164_1_, _165_1_, _166_1_, _167_1_; }; unsigned int _164_4_; };
        union { struct { unsigned char _168_1_, _169_1_, _170_1_, _171_1_; }; unsigned int _168_4_; };
        union { struct { unsigned char _172_1_, _173_1_, _174_1_, _175_1_; }; unsigned int _172_4_; };
        union { struct { unsigned char _176_1_, _177_1_, _178_1_, _179_1_; }; unsigned int _176_4_; };
        union { struct { unsigned char _180_1_, _181_1_, _182_1_, _183_1_; }; unsigned int _180_4_; };
        union { struct { unsigned char _184_1_, _185_1_, _186_1_, _187_1_; }; unsigned int _184_4_; };
        union { struct { unsigned char _188_1_, _189_1_, _190_1_, _191_1_; }; unsigned int _188_4_; };
        union { struct { unsigned char _192_1_, _193_1_, _194_1_, _195_1_; }; unsigned int _192_4_; };
        union { struct { unsigned char _196_1_, _197_1_, _198_1_, _199_1_; }; unsigned int _196_4_; };
        union { struct { unsigned char _200_1_, _201_1_, _202_1_, _203_1_; }; unsigned int _200_4_; };
        union { struct { unsigned char _204_1_, _205_1_, _206_1_, _207_1_; }; unsigned int _204_4_; };
        union { struct { unsigned char _208_1_, _209_1_, _210_1_, _211_1_; }; unsigned int _208_4_; };
        union { struct { unsigned char _212_1_, _213_1_, _214_1_, _215_1_; }; unsigned int _212_4_; };
        union { struct { unsigned char _216_1_, _217_1_, _218_1_, _219_1_; }; unsigned int _216_4_; };
        union { struct { unsigned char _220_1_, _221_1_, _222_1_, _223_1_; }; unsigned int _220_4_; };
        union { struct { unsigned char _224_1_, _225_1_, _226_1_, _227_1_; }; unsigned int _224_4_; };
        union { struct { unsigned char _228_1_, _229_1_, _230_1_, _231_1_; }; unsigned int _228_4_; };
        union { struct { unsigned char _232_1_, _233_1_, _234_1_, _235_1_; }; unsigned int _232_4_; };
        union { struct { unsigned char _236_1_, _237_1_, _238_1_, _239_1_; }; unsigned int _236_4_; };
        union { struct { unsigned char _240_1_, _241_1_, _242_1_, _243_1_; }; unsigned int _240_4_; };
        union { struct { unsigned char _244_1_, _245_1_, _246_1_, _247_1_; }; unsigned int _244_4_; };
        union { struct { unsigned char _248_1_, _249_1_, _250_1_, _251_1_; }; unsigned int _248_4_; };
        union { struct { unsigned char _252_1_, _253_1_, _254_1_, _255_1_; }; unsigned int _252_4_; };
        union { struct { unsigned char _256_1_, _257_1_, _258_1_, _259_1_; }; unsigned int _256_4_; };
        union { struct { unsigned char _260_1_, _261_1_, _262_1_, _263_1_; }; unsigned int _260_4_; };
        union { struct { unsigned char _264_1_, _265_1_, _266_1_, _267_1_; }; unsigned int _264_4_; };
        union { struct { unsigned char _268_1_, _269_1_, _270_1_, _271_1_; }; unsigned int _268_4_; };
        union { struct { unsigned char _272_1_, _273_1_, _274_1_, _275_1_; }; unsigned int _272_4_; };
        union { struct { unsigned char _276_1_, _277_1_, _278_1_, _279_1_; }; unsigned int _276_4_; };
        union { struct { unsigned char _280_1_, _281_1_, _282_1_, _283_1_; }; unsigned int _280_4_; };
        union { struct { unsigned char _284_1_, _285_1_, _286_1_, _287_1_; }; unsigned int _284_4_; };
        union { struct { unsigned char _288_1_, _289_1_, _290_1_, _291_1_; }; unsigned int _288_4_; };
        union { struct { unsigned char _292_1_, _293_1_, _294_1_, _295_1_; }; unsigned int _292_4_; };
        union { struct { unsigned char _296_1_, _297_1_, _298_1_, _299_1_; }; unsigned int _296_4_; };
        union { struct { unsigned char _300_1_, _301_1_, _302_1_, _303_1_; }; unsigned int _300_4_; };
        union { struct { unsigned char _304_1_, _305_1_, _306_1_, _307_1_; }; unsigned int _304_4_; };
        union { struct { unsigned char _308_1_, _309_1_, _310_1_, _311_1_; }; unsigned int _308_4_; };
        union { struct { unsigned char _312_1_, _313_1_, _314_1_, _315_1_; }; unsigned int _312_4_; };
        union { struct { unsigned char _316_1_, _317_1_, _318_1_, _319_1_; }; unsigned int _316_4_; };
        union { struct { unsigned char _320_1_, _321_1_, _322_1_, _323_1_; }; unsigned int _320_4_; };
        union { struct { unsigned char _324_1_, _325_1_, _326_1_, _327_1_; }; unsigned int _324_4_; };
        union { struct { unsigned char _328_1_, _329_1_, _330_1_, _331_1_; }; unsigned int _328_4_; };
        union { struct { unsigned char _332_1_, _333_1_, _334_1_, _335_1_; }; unsigned int _332_4_; };
        union { struct { unsigned char _336_1_, _337_1_, _338_1_, _339_1_; }; unsigned int _336_4_; };
        union { struct { unsigned char _340_1_, _341_1_, _342_1_, _343_1_; }; unsigned int _340_4_; };
        union { struct { unsigned char _344_1_, _345_1_, _346_1_, _347_1_; }; unsigned int _344_4_; };
        union { struct { unsigned char _348_1_, _349_1_, _350_1_, _351_1_; }; unsigned int _348_4_; };
        union { struct { unsigned char _352_1_, _353_1_, _354_1_, _355_1_; }; unsigned int _352_4_; };
        union { struct { unsigned char _356_1_, _357_1_, _358_1_, _359_1_; }; unsigned int _356_4_; };
        union { struct { unsigned char _360_1_, _361_1_, _362_1_, _363_1_; }; unsigned int _360_4_; };
        union { struct { unsigned char _364_1_, _365_1_, _366_1_, _367_1_; }; unsigned int _364_4_; };
        union { struct { unsigned char _368_1_, _369_1_, _370_1_, _371_1_; }; unsigned int _368_4_; };
        union { struct { unsigned char _372_1_, _373_1_, _374_1_, _375_1_; }; unsigned int _372_4_; };
        union { struct { unsigned char _376_1_, _377_1_, _378_1_, _379_1_; }; unsigned int _376_4_; };
        union { struct { unsigned char _380_1_, _381_1_, _382_1_, _383_1_; }; unsigned int _380_4_; };
        union { struct { unsigned char _384_1_, _385_1_, _386_1_, _387_1_; }; unsigned int _384_4_; };
        union { struct { unsigned char _388_1_, _389_1_, _390_1_, _391_1_; }; unsigned int _388_4_; };
        union { struct { unsigned char _392_1_, _393_1_, _394_1_, _395_1_; }; unsigned int _392_4_; };
        union { struct { unsigned char _396_1_, _397_1_, _398_1_, _399_1_; }; unsigned int _396_4_; };
        union { struct { unsigned char _400_1_, _401_1_, _402_1_, _403_1_; }; unsigned int _400_4_; };
        union { struct { unsigned char _404_1_, _405_1_, _406_1_, _407_1_; }; unsigned int _404_4_; };
        union { struct { unsigned char _408_1_, _409_1_, _410_1_, _411_1_; }; unsigned int _408_4_; };
        union { struct { unsigned char _412_1_, _413_1_, _414_1_, _415_1_; }; unsigned int _412_4_; };
        union { struct { unsigned char _416_1_, _417_1_, _418_1_, _419_1_; }; unsigned int _416_4_; };
        union { struct { unsigned char _420_1_, _421_1_, _422_1_, _423_1_; }; unsigned int _420_4_; };
        union { struct { unsigned char _424_1_, _425_1_, _426_1_, _427_1_; }; unsigned int _424_4_; };
        union { struct { unsigned char _428_1_, _429_1_, _430_1_, _431_1_; }; unsigned int _428_4_; };
        union { struct { unsigned char _432_1_, _433_1_, _434_1_, _435_1_; }; unsigned int _432_4_; };
        union { struct { unsigned char _436_1_, _437_1_, _438_1_, _439_1_; }; unsigned int _436_4_; };
        union { struct { unsigned char _440_1_, _441_1_, _442_1_, _443_1_; }; unsigned int _440_4_; };
        union { struct { unsigned char _444_1_, _445_1_, _446_1_, _447_1_; }; unsigned int _444_4_; };
        union { struct { unsigned char _448_1_, _449_1_, _450_1_, _451_1_; }; unsigned int _448_4_; };
        union { struct { unsigned char _452_1_, _453_1_, _454_1_, _455_1_; }; unsigned int _452_4_; };
        union { struct { unsigned char _456_1_, _457_1_, _458_1_, _459_1_; }; unsigned int _456_4_; };
        union { struct { unsigned char _460_1_, _461_1_, _462_1_, _463_1_; }; unsigned int _460_4_; };
        union { struct { unsigned char _464_1_, _465_1_, _466_1_, _467_1_; }; unsigned int _464_4_; };
        union { struct { unsigned char _468_1_, _469_1_, _470_1_, _471_1_; }; unsigned int _468_4_; };
        union { struct { unsigned char _472_1_, _473_1_, _474_1_, _475_1_; }; unsigned int _472_4_; };
        union { struct { unsigned char _476_1_, _477_1_, _478_1_, _479_1_; }; unsigned int _476_4_; };
        union { struct { unsigned char _480_1_, _481_1_, _482_1_, _483_1_; }; unsigned int _480_4_; };
        union { struct { unsigned char _484_1_, _485_1_, _486_1_, _487_1_; }; unsigned int _484_4_; };
        union { struct { unsigned char _488_1_, _489_1_, _490_1_, _491_1_; }; unsigned int _488_4_; };
        union { struct { unsigned char _492_1_, _493_1_, _494_1_, _495_1_; }; unsigned int _492_4_; };
        union { struct { unsigned char _496_1_, _497_1_, _498_1_, _499_1_; }; unsigned int _496_4_; };
        union { struct { unsigned char _500_1_, _501_1_, _502_1_, _503_1_; }; unsigned int _500_4_; };
        union { struct { unsigned char _504_1_, _505_1_, _506_1_, _507_1_; }; unsigned int _504_4_; };
        union { struct { unsigned char _508_1_, _509_1_, _510_1_, _511_1_; }; unsigned int _508_4_; };
        union { struct { unsigned char _512_1_, _513_1_, _514_1_, _515_1_; }; unsigned int _512_4_; };
        union { struct { unsigned char _516_1_, _517_1_, _518_1_, _519_1_; }; unsigned int _516_4_; };
        union { struct { unsigned char _520_1_, _521_1_, _522_1_, _523_1_; }; unsigned int _520_4_; };
        union { struct { unsigned char _524_1_, _525_1_, _526_1_, _527_1_; }; unsigned int _524_4_; };
        union { struct { unsigned char _528_1_, _529_1_, _530_1_, _531_1_; }; unsigned int _528_4_; };
        union { struct { unsigned char _532_1_, _533_1_, _534_1_, _535_1_; }; unsigned int _532_4_; };
        union { struct { unsigned char _536_1_, _537_1_, _538_1_, _539_1_; }; unsigned int _536_4_; };
        union { struct { unsigned char _540_1_, _541_1_, _542_1_, _543_1_; }; unsigned int _540_4_; };
        union { struct { unsigned char _544_1_, _545_1_, _546_1_, _547_1_; }; unsigned int _544_4_; };
        union { struct { unsigned char _548_1_, _549_1_, _550_1_, _551_1_; }; unsigned int _548_4_; };
        union { struct { unsigned char _552_1_, _553_1_, _554_1_, _555_1_; }; unsigned int _552_4_; };
        union { struct { unsigned char _556_1_, _557_1_, _558_1_, _559_1_; }; unsigned int _556_4_; };
        union { struct { unsigned char _560_1_, _561_1_, _562_1_, _563_1_; }; unsigned int _560_4_; };
        union { struct { unsigned char _564_1_, _565_1_, _566_1_, _567_1_; }; unsigned int _564_4_; };
        union { struct { unsigned char _568_1_, _569_1_, _570_1_, _571_1_; }; unsigned int _568_4_; };
        union { struct { unsigned char _572_1_, _573_1_, _574_1_, _575_1_; }; unsigned int _572_4_; };
        union { struct { unsigned char _576_1_, _577_1_, _578_1_, _579_1_; }; unsigned int _576_4_; };
        union { struct { unsigned char _580_1_, _581_1_, _582_1_, _583_1_; }; unsigned int _580_4_; };
        union { struct { unsigned char _584_1_, _585_1_, _586_1_, _587_1_; }; unsigned int _584_4_; };
        union { struct { unsigned char _588_1_, _589_1_, _590_1_, _591_1_; }; unsigned int _588_4_; };
        union { struct { unsigned char _592_1_, _593_1_, _594_1_, _595_1_; }; unsigned int _592_4_; };
        union { struct { unsigned char _596_1_, _597_1_, _598_1_, _599_1_; }; unsigned int _596_4_; };
        union { struct { unsigned char _600_1_, _601_1_, _602_1_, _603_1_; }; unsigned int _600_4_; };
        union { struct { unsigned char _604_1_, _605_1_, _606_1_, _607_1_; }; unsigned int _604_4_; };
        union { struct { unsigned char _608_1_, _609_1_, _610_1_, _611_1_; }; unsigned int _608_4_; };
        union { struct { unsigned char _612_1_, _613_1_, _614_1_, _615_1_; }; unsigned int _612_4_; };
        union { struct { unsigned char _616_1_, _617_1_, _618_1_, _619_1_; }; unsigned int _616_4_; };
        union { struct { unsigned char _620_1_, _621_1_, _622_1_, _623_1_; }; unsigned int _620_4_; };
        union { struct { unsigned char _624_1_, _625_1_, _626_1_, _627_1_; }; unsigned int _624_4_; };
        union { struct { unsigned char _628_1_, _629_1_, _630_1_, _631_1_; }; unsigned int _628_4_; };
        union { struct { unsigned char _632_1_, _633_1_, _634_1_, _635_1_; }; unsigned int _632_4_; };
        union { struct { unsigned char _636_1_, _637_1_, _638_1_, _639_1_; }; unsigned int _636_4_; };
        union { struct { unsigned char _640_1_, _641_1_, _642_1_, _643_1_; }; unsigned int _640_4_; };
        union { struct { unsigned char _644_1_, _645_1_, _646_1_, _647_1_; }; unsigned int _644_4_; };
        union { struct { unsigned char _648_1_, _649_1_, _650_1_, _651_1_; }; unsigned int _648_4_; };
        union { struct { unsigned char _652_1_, _653_1_, _654_1_, _655_1_; }; unsigned int _652_4_; };
        union { struct { unsigned char _656_1_, _657_1_, _658_1_, _659_1_; }; unsigned int _656_4_; };
        union { struct { unsigned char _660_1_, _661_1_, _662_1_, _663_1_; }; unsigned int _660_4_; };
        union { struct { unsigned char _664_1_, _665_1_, _666_1_, _667_1_; }; unsigned int _664_4_; };
        union { struct { unsigned char _668_1_, _669_1_, _670_1_, _671_1_; }; unsigned int _668_4_; };
        union { struct { unsigned char _672_1_, _673_1_, _674_1_, _675_1_; }; unsigned int _672_4_; };
        union { struct { unsigned char _676_1_, _677_1_, _678_1_, _679_1_; }; unsigned int _676_4_; };
        union { struct { unsigned char _680_1_, _681_1_, _682_1_, _683_1_; }; unsigned int _680_4_; };
        union { struct { unsigned char _684_1_, _685_1_, _686_1_, _687_1_; }; unsigned int _684_4_; };
        union { struct { unsigned char _688_1_, _689_1_, _690_1_, _691_1_; }; unsigned int _688_4_; };
        union { struct { unsigned char _692_1_, _693_1_, _694_1_, _695_1_; }; unsigned int _692_4_; };
        union { struct { unsigned char _696_1_, _697_1_, _698_1_, _699_1_; }; unsigned int _696_4_; };
        union { struct { unsigned char _700_1_, _701_1_, _702_1_, _703_1_; }; unsigned int _700_4_; };
        union { struct { unsigned char _704_1_, _705_1_, _706_1_, _707_1_; }; unsigned int _704_4_; };
        union { struct { unsigned char _708_1_, _709_1_, _710_1_, _711_1_; }; unsigned int _708_4_; };
        union { struct { unsigned char _712_1_, _713_1_, _714_1_, _715_1_; }; unsigned int _712_4_; };
        union { struct { unsigned char _716_1_, _717_1_, _718_1_, _719_1_; }; unsigned int _716_4_; };
        union { struct { unsigned char _720_1_, _721_1_, _722_1_, _723_1_; }; unsigned int _720_4_; };
        union { struct { unsigned char _724_1_, _725_1_, _726_1_, _727_1_; }; unsigned int _724_4_; };
        union { struct { unsigned char _728_1_, _729_1_, _730_1_, _731_1_; }; unsigned int _728_4_; };
        union { struct { unsigned char _732_1_, _733_1_, _734_1_, _735_1_; }; unsigned int _732_4_; };
        union { struct { unsigned char _736_1_, _737_1_, _738_1_, _739_1_; }; unsigned int _736_4_; };
        union { struct { unsigned char _740_1_, _741_1_, _742_1_, _743_1_; }; unsigned int _740_4_; };
        union { struct { unsigned char _744_1_, _745_1_, _746_1_, _747_1_; }; unsigned int _744_4_; };
        union { struct { unsigned char _748_1_, _749_1_, _750_1_, _751_1_; }; unsigned int _748_4_; };
        union { struct { unsigned char _752_1_, _753_1_, _754_1_, _755_1_; }; unsigned int _752_4_; };
        union { struct { unsigned char _756_1_, _757_1_, _758_1_, _759_1_; }; unsigned int _756_4_; };
        union { struct { unsigned char _760_1_, _761_1_, _762_1_, _763_1_; }; unsigned int _760_4_; };
        union { struct { unsigned char _764_1_, _765_1_, _766_1_, _767_1_; }; unsigned int _764_4_; };
        union { struct { unsigned char _768_1_, _769_1_, _770_1_, _771_1_; }; unsigned int _768_4_; };
        union { struct { unsigned char _772_1_, _773_1_, _774_1_, _775_1_; }; unsigned int _772_4_; };
        union { struct { unsigned char _776_1_, _777_1_, _778_1_, _779_1_; }; unsigned int _776_4_; };
        union { struct { unsigned char _780_1_, _781_1_, _782_1_, _783_1_; }; unsigned int _780_4_; };
        union { struct { unsigned char _784_1_, _785_1_, _786_1_, _787_1_; }; unsigned int _784_4_; };
        union { struct { unsigned char _788_1_, _789_1_, _790_1_, _791_1_; }; unsigned int _788_4_; };
        union { struct { unsigned char _792_1_, _793_1_, _794_1_, _795_1_; }; unsigned int _792_4_; };
        union { struct { unsigned char _796_1_, _797_1_, _798_1_, _799_1_; }; unsigned int _796_4_; };
        union { struct { unsigned char _800_1_, _801_1_, _802_1_, _803_1_; }; unsigned int _800_4_; };
        union { struct { unsigned char _804_1_, _805_1_, _806_1_, _807_1_; }; unsigned int _804_4_; };
        union { struct { unsigned char _808_1_, _809_1_, _810_1_, _811_1_; }; unsigned int _808_4_; };
        union { struct { unsigned char _812_1_, _813_1_, _814_1_, _815_1_; }; unsigned int _812_4_; };
        union { struct { unsigned char _816_1_, _817_1_, _818_1_, _819_1_; }; unsigned int _816_4_; };
        union { struct { unsigned char _820_1_, _821_1_, _822_1_, _823_1_; }; unsigned int _820_4_; };
        union { struct { unsigned char _824_1_, _825_1_, _826_1_, _827_1_; }; unsigned int _824_4_; };
        union { struct { unsigned char _828_1_, _829_1_, _830_1_, _831_1_; }; unsigned int _828_4_; };
        union { struct { unsigned char _832_1_, _833_1_, _834_1_, _835_1_; }; unsigned int _832_4_; };
        union { struct { unsigned char _836_1_, _837_1_, _838_1_, _839_1_; }; unsigned int _836_4_; };
        union { struct { unsigned char _840_1_, _841_1_, _842_1_, _843_1_; }; unsigned int _840_4_; };
        union { struct { unsigned char _844_1_, _845_1_, _846_1_, _847_1_; }; unsigned int _844_4_; };
        union { struct { unsigned char _848_1_, _849_1_, _850_1_, _851_1_; }; unsigned int _848_4_; };
        union { struct { unsigned char _852_1_, _853_1_, _854_1_, _855_1_; }; unsigned int _852_4_; };
        union { struct { unsigned char _856_1_, _857_1_, _858_1_, _859_1_; }; unsigned int _856_4_; };
        union { struct { unsigned char _860_1_, _861_1_, _862_1_, _863_1_; }; unsigned int _860_4_; };
        union { struct { unsigned char _864_1_, _865_1_, _866_1_, _867_1_; }; unsigned int _864_4_; };
        union { struct { unsigned char _868_1_, _869_1_, _870_1_, _871_1_; }; unsigned int _868_4_; };
        union { struct { unsigned char _872_1_, _873_1_, _874_1_, _875_1_; }; unsigned int _872_4_; };
        union { struct { unsigned char _876_1_, _877_1_, _878_1_, _879_1_; }; unsigned int _876_4_; };
        union { struct { unsigned char _880_1_, _881_1_, _882_1_, _883_1_; }; unsigned int _880_4_; };
        union { struct { unsigned char _884_1_, _885_1_, _886_1_, _887_1_; }; unsigned int _884_4_; };
        union { struct { unsigned char _888_1_, _889_1_, _890_1_, _891_1_; }; unsigned int _888_4_; };
        union { struct { unsigned char _892_1_, _893_1_, _894_1_, _895_1_; }; unsigned int _892_4_; };
        union { struct { unsigned char _896_1_, _897_1_, _898_1_, _899_1_; }; unsigned int _896_4_; };
        union { struct { unsigned char _900_1_, _901_1_, _902_1_, _903_1_; }; unsigned int _900_4_; };
        union { struct { unsigned char _904_1_, _905_1_, _906_1_, _907_1_; }; unsigned int _904_4_; };
        union { struct { unsigned char _908_1_, _909_1_, _910_1_, _911_1_; }; unsigned int _908_4_; };
        union { struct { unsigned char _912_1_, _913_1_, _914_1_, _915_1_; }; unsigned int _912_4_; };
        union { struct { unsigned char _916_1_, _917_1_, _918_1_, _919_1_; }; unsigned int _916_4_; };
        union { struct { unsigned char _920_1_, _921_1_, _922_1_, _923_1_; }; unsigned int _920_4_; };
    };
} m_joysticktab_t;
#define m_joysticktab_blob (*(m_joysticktab_t*)&m_joysticktab)

typedef union {
    unsigned char raw[444];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
        union { struct { unsigned char _72_1_, _73_1_, _74_1_, _75_1_; }; unsigned int _72_4_; };
        union { struct { unsigned char _76_1_, _77_1_, _78_1_, _79_1_; }; unsigned int _76_4_; };
        union { struct { unsigned char _80_1_, _81_1_, _82_1_, _83_1_; }; unsigned int _80_4_; };
        union { struct { unsigned char _84_1_, _85_1_, _86_1_, _87_1_; }; unsigned int _84_4_; };
        union { struct { unsigned char _88_1_, _89_1_, _90_1_, _91_1_; }; unsigned int _88_4_; };
        union { struct { unsigned char _92_1_, _93_1_, _94_1_, _95_1_; }; unsigned int _92_4_; };
        union { struct { unsigned char _96_1_, _97_1_, _98_1_, _99_1_; }; unsigned int _96_4_; };
        union { struct { unsigned char _100_1_, _101_1_, _102_1_, _103_1_; }; unsigned int _100_4_; };
        union { struct { unsigned char _104_1_, _105_1_, _106_1_, _107_1_; }; unsigned int _104_4_; };
        union { struct { unsigned char _108_1_, _109_1_, _110_1_, _111_1_; }; unsigned int _108_4_; };
        union { struct { unsigned char _112_1_, _113_1_, _114_1_, _115_1_; }; unsigned int _112_4_; };
        union { struct { unsigned char _116_1_, _117_1_, _118_1_, _119_1_; }; unsigned int _116_4_; };
        union { struct { unsigned char _120_1_, _121_1_, _122_1_, _123_1_; }; unsigned int _120_4_; };
        union { struct { unsigned char _124_1_, _125_1_, _126_1_, _127_1_; }; unsigned int _124_4_; };
        union { struct { unsigned char _128_1_, _129_1_, _130_1_, _131_1_; }; unsigned int _128_4_; };
        union { struct { unsigned char _132_1_, _133_1_, _134_1_, _135_1_; }; unsigned int _132_4_; };
        union { struct { unsigned char _136_1_, _137_1_, _138_1_, _139_1_; }; unsigned int _136_4_; };
        union { struct { unsigned char _140_1_, _141_1_, _142_1_, _143_1_; }; unsigned int _140_4_; };
        union { struct { unsigned char _144_1_, _145_1_, _146_1_, _147_1_; }; unsigned int _144_4_; };
        union { struct { unsigned char _148_1_, _149_1_, _150_1_, _151_1_; }; unsigned int _148_4_; };
        union { struct { unsigned char _152_1_, _153_1_, _154_1_, _155_1_; }; unsigned int _152_4_; };
        union { struct { unsigned char _156_1_, _157_1_, _158_1_, _159_1_; }; unsigned int _156_4_; };
        union { struct { unsigned char _160_1_, _161_1_, _162_1_, _163_1_; }; unsigned int _160_4_; };
        union { struct { unsigned char _164_1_, _165_1_, _166_1_, _167_1_; }; unsigned int _164_4_; };
        union { struct { unsigned char _168_1_, _169_1_, _170_1_, _171_1_; }; unsigned int _168_4_; };
        union { struct { unsigned char _172_1_, _173_1_, _174_1_, _175_1_; }; unsigned int _172_4_; };
        union { struct { unsigned char _176_1_, _177_1_, _178_1_, _179_1_; }; unsigned int _176_4_; };
        union { struct { unsigned char _180_1_, _181_1_, _182_1_, _183_1_; }; unsigned int _180_4_; };
        union { struct { unsigned char _184_1_, _185_1_, _186_1_, _187_1_; }; unsigned int _184_4_; };
        union { struct { unsigned char _188_1_, _189_1_, _190_1_, _191_1_; }; unsigned int _188_4_; };
        union { struct { unsigned char _192_1_, _193_1_, _194_1_, _195_1_; }; unsigned int _192_4_; };
        union { struct { unsigned char _196_1_, _197_1_, _198_1_, _199_1_; }; unsigned int _196_4_; };
        union { struct { unsigned char _200_1_, _201_1_, _202_1_, _203_1_; }; unsigned int _200_4_; };
        union { struct { unsigned char _204_1_, _205_1_, _206_1_, _207_1_; }; unsigned int _204_4_; };
        union { struct { unsigned char _208_1_, _209_1_, _210_1_, _211_1_; }; unsigned int _208_4_; };
        union { struct { unsigned char _212_1_, _213_1_, _214_1_, _215_1_; }; unsigned int _212_4_; };
        union { struct { unsigned char _216_1_, _217_1_, _218_1_, _219_1_; }; unsigned int _216_4_; };
        union { struct { unsigned char _220_1_, _221_1_, _222_1_, _223_1_; }; unsigned int _220_4_; };
        union { struct { unsigned char _224_1_, _225_1_, _226_1_, _227_1_; }; unsigned int _224_4_; };
        union { struct { unsigned char _228_1_, _229_1_, _230_1_, _231_1_; }; unsigned int _228_4_; };
        union { struct { unsigned char _232_1_, _233_1_, _234_1_, _235_1_; }; unsigned int _232_4_; };
        union { struct { unsigned char _236_1_, _237_1_, _238_1_, _239_1_; }; unsigned int _236_4_; };
        union { struct { unsigned char _240_1_, _241_1_, _242_1_, _243_1_; }; unsigned int _240_4_; };
        union { struct { unsigned char _244_1_, _245_1_, _246_1_, _247_1_; }; unsigned int _244_4_; };
        union { struct { unsigned char _248_1_, _249_1_, _250_1_, _251_1_; }; unsigned int _248_4_; };
        union { struct { unsigned char _252_1_, _253_1_, _254_1_, _255_1_; }; unsigned int _252_4_; };
        union { struct { unsigned char _256_1_, _257_1_, _258_1_, _259_1_; }; unsigned int _256_4_; };
        union { struct { unsigned char _260_1_, _261_1_, _262_1_, _263_1_; }; unsigned int _260_4_; };
        union { struct { unsigned char _264_1_, _265_1_, _266_1_, _267_1_; }; unsigned int _264_4_; };
        union { struct { unsigned char _268_1_, _269_1_, _270_1_, _271_1_; }; unsigned int _268_4_; };
        union { struct { unsigned char _272_1_, _273_1_, _274_1_, _275_1_; }; unsigned int _272_4_; };
        union { struct { unsigned char _276_1_, _277_1_, _278_1_, _279_1_; }; unsigned int _276_4_; };
        union { struct { unsigned char _280_1_, _281_1_, _282_1_, _283_1_; }; unsigned int _280_4_; };
        union { struct { unsigned char _284_1_, _285_1_, _286_1_, _287_1_; }; unsigned int _284_4_; };
        union { struct { unsigned char _288_1_, _289_1_, _290_1_, _291_1_; }; unsigned int _288_4_; };
        union { struct { unsigned char _292_1_, _293_1_, _294_1_, _295_1_; }; unsigned int _292_4_; };
        union { struct { unsigned char _296_1_, _297_1_, _298_1_, _299_1_; }; unsigned int _296_4_; };
        union { struct { unsigned char _300_1_, _301_1_, _302_1_, _303_1_; }; unsigned int _300_4_; };
        union { struct { unsigned char _304_1_, _305_1_, _306_1_, _307_1_; }; unsigned int _304_4_; };
        union { struct { unsigned char _308_1_, _309_1_, _310_1_, _311_1_; }; unsigned int _308_4_; };
        union { struct { unsigned char _312_1_, _313_1_, _314_1_, _315_1_; }; unsigned int _312_4_; };
        union { struct { unsigned char _316_1_, _317_1_, _318_1_, _319_1_; }; unsigned int _316_4_; };
        union { struct { unsigned char _320_1_, _321_1_, _322_1_, _323_1_; }; unsigned int _320_4_; };
        union { struct { unsigned char _324_1_, _325_1_, _326_1_, _327_1_; }; unsigned int _324_4_; };
        union { struct { unsigned char _328_1_, _329_1_, _330_1_, _331_1_; }; unsigned int _328_4_; };
        union { struct { unsigned char _332_1_, _333_1_, _334_1_, _335_1_; }; unsigned int _332_4_; };
        union { struct { unsigned char _336_1_, _337_1_, _338_1_, _339_1_; }; unsigned int _336_4_; };
        union { struct { unsigned char _340_1_, _341_1_, _342_1_, _343_1_; }; unsigned int _340_4_; };
        union { struct { unsigned char _344_1_, _345_1_, _346_1_, _347_1_; }; unsigned int _344_4_; };
        union { struct { unsigned char _348_1_, _349_1_, _350_1_, _351_1_; }; unsigned int _348_4_; };
        union { struct { unsigned char _352_1_, _353_1_, _354_1_, _355_1_; }; unsigned int _352_4_; };
        union { struct { unsigned char _356_1_, _357_1_, _358_1_, _359_1_; }; unsigned int _356_4_; };
        union { struct { unsigned char _360_1_, _361_1_, _362_1_, _363_1_; }; unsigned int _360_4_; };
        union { struct { unsigned char _364_1_, _365_1_, _366_1_, _367_1_; }; unsigned int _364_4_; };
        union { struct { unsigned char _368_1_, _369_1_, _370_1_, _371_1_; }; unsigned int _368_4_; };
        union { struct { unsigned char _372_1_, _373_1_, _374_1_, _375_1_; }; unsigned int _372_4_; };
        union { struct { unsigned char _376_1_, _377_1_, _378_1_, _379_1_; }; unsigned int _376_4_; };
        union { struct { unsigned char _380_1_, _381_1_, _382_1_, _383_1_; }; unsigned int _380_4_; };
        union { struct { unsigned char _384_1_, _385_1_, _386_1_, _387_1_; }; unsigned int _384_4_; };
        union { struct { unsigned char _388_1_, _389_1_, _390_1_, _391_1_; }; unsigned int _388_4_; };
        union { struct { unsigned char _392_1_, _393_1_, _394_1_, _395_1_; }; unsigned int _392_4_; };
        union { struct { unsigned char _396_1_, _397_1_, _398_1_, _399_1_; }; unsigned int _396_4_; };
        union { struct { unsigned char _400_1_, _401_1_, _402_1_, _403_1_; }; unsigned int _400_4_; };
        union { struct { unsigned char _404_1_, _405_1_, _406_1_, _407_1_; }; unsigned int _404_4_; };
        union { struct { unsigned char _408_1_, _409_1_, _410_1_, _411_1_; }; unsigned int _408_4_; };
        union { struct { unsigned char _412_1_, _413_1_, _414_1_, _415_1_; }; unsigned int _412_4_; };
        union { struct { unsigned char _416_1_, _417_1_, _418_1_, _419_1_; }; unsigned int _416_4_; };
        union { struct { unsigned char _420_1_, _421_1_, _422_1_, _423_1_; }; unsigned int _420_4_; };
        union { struct { unsigned char _424_1_, _425_1_, _426_1_, _427_1_; }; unsigned int _424_4_; };
        union { struct { unsigned char _428_1_, _429_1_, _430_1_, _431_1_; }; unsigned int _428_4_; };
        union { struct { unsigned char _432_1_, _433_1_, _434_1_, _435_1_; }; unsigned int _432_4_; };
        union { struct { unsigned char _436_1_, _437_1_, _438_1_, _439_1_; }; unsigned int _436_4_; };
        union { struct { unsigned char _440_1_, _441_1_, _442_1_, _443_1_; }; unsigned int _440_4_; };
    };
} m_menulog_t;
#define m_menulog_blob (*(m_menulog_t*)&m_menulog)

typedef union {
    unsigned char raw[144];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
        union { struct { unsigned char _72_1_, _73_1_, _74_1_, _75_1_; }; unsigned int _72_4_; };
        union { struct { unsigned char _76_1_, _77_1_, _78_1_, _79_1_; }; unsigned int _76_4_; };
        union { struct { unsigned char _80_1_, _81_1_, _82_1_, _83_1_; }; unsigned int _80_4_; };
        union { struct { unsigned char _84_1_, _85_1_, _86_1_, _87_1_; }; unsigned int _84_4_; };
        union { struct { unsigned char _88_1_, _89_1_, _90_1_, _91_1_; }; unsigned int _88_4_; };
        union { struct { unsigned char _92_1_, _93_1_, _94_1_, _95_1_; }; unsigned int _92_4_; };
        union { struct { unsigned char _96_1_, _97_1_, _98_1_, _99_1_; }; unsigned int _96_4_; };
        union { struct { unsigned char _100_1_, _101_1_, _102_1_, _103_1_; }; unsigned int _100_4_; };
        union { struct { unsigned char _104_1_, _105_1_, _106_1_, _107_1_; }; unsigned int _104_4_; };
        union { struct { unsigned char _108_1_, _109_1_, _110_1_, _111_1_; }; unsigned int _108_4_; };
        union { struct { unsigned char _112_1_, _113_1_, _114_1_, _115_1_; }; unsigned int _112_4_; };
        union { struct { unsigned char _116_1_, _117_1_, _118_1_, _119_1_; }; unsigned int _116_4_; };
        union { struct { unsigned char _120_1_, _121_1_, _122_1_, _123_1_; }; unsigned int _120_4_; };
        union { struct { unsigned char _124_1_, _125_1_, _126_1_, _127_1_; }; unsigned int _124_4_; };
        union { struct { unsigned char _128_1_, _129_1_, _130_1_, _131_1_; }; unsigned int _128_4_; };
        union { struct { unsigned char _132_1_, _133_1_, _134_1_, _135_1_; }; unsigned int _132_4_; };
        union { struct { unsigned char _136_1_, _137_1_, _138_1_, _139_1_; }; unsigned int _136_4_; };
        union { struct { unsigned char _140_1_, _141_1_, _142_1_, _143_1_; }; unsigned int _140_4_; };
    };
} m_statetab_t;
#define m_statetab_blob (*(m_statetab_t*)&m_statetab)

typedef union {
    unsigned char raw[112];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
        union { struct { unsigned char _72_1_, _73_1_, _74_1_, _75_1_; }; unsigned int _72_4_; };
        union { struct { unsigned char _76_1_, _77_1_, _78_1_, _79_1_; }; unsigned int _76_4_; };
        union { struct { unsigned char _80_1_, _81_1_, _82_1_, _83_1_; }; unsigned int _80_4_; };
        union { struct { unsigned char _84_1_, _85_1_, _86_1_, _87_1_; }; unsigned int _84_4_; };
        union { struct { unsigned char _88_1_, _89_1_, _90_1_, _91_1_; }; unsigned int _88_4_; };
        union { struct { unsigned char _92_1_, _93_1_, _94_1_, _95_1_; }; unsigned int _92_4_; };
        union { struct { unsigned char _96_1_, _97_1_, _98_1_, _99_1_; }; unsigned int _96_4_; };
        union { struct { unsigned char _100_1_, _101_1_, _102_1_, _103_1_; }; unsigned int _100_4_; };
        union { struct { unsigned char _104_1_, _105_1_, _106_1_, _107_1_; }; unsigned int _104_4_; };
        union { struct { unsigned char _108_1_, _109_1_, _110_1_, _111_1_; }; unsigned int _108_4_; };
    };
} InputDeviceInfo_t;
#define InputDeviceInfo_blob (*(InputDeviceInfo_t*)&InputDeviceInfo)

typedef union {
    unsigned char raw[72];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
    };
} SoundPlayer_t;
#define SoundPlayer_blob (*(SoundPlayer_t*)&SoundPlayer)

typedef union {
    unsigned char raw[64];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
    };
} fpsbuf_t;
#define fpsbuf_blob (*(fpsbuf_t*)&fpsbuf)

typedef union {
    unsigned char raw[16];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
    };
} game_joy_key_t;
#define game_joy_key_blob (*(game_joy_key_t*)&game_joy_key)

typedef union {
    unsigned char raw[16];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
    };
} joy_key_t;
#define joy_key_blob (*(joy_key_t*)&joy_key)

typedef union {
    unsigned char raw[16];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
    };
} game_t;
/* 修正：_0_4_/_4_4_ 分别对应 retro_game_info.path / .data（指针），仅 _8_4_ 为 size */
typedef union {
    unsigned char raw[16];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; void *_0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; void *_4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        unsigned int _12_4_;
    };
} game_ptr_t;
#define game_blob (*(game_ptr_t*)&game)

typedef union {
    unsigned char raw[36];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
    };
} mui_Effect0_t;
#define mui_Effect0_blob (*(mui_Effect0_t*)&mui_Effect0)

typedef union {
    unsigned char raw[36];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
    };
} mui_Effect1_t;
#define mui_Effect1_blob (*(mui_Effect1_t*)&mui_Effect1)

typedef union {
    unsigned char raw[36];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
    };
} mui_MenuMusic_t;
#define mui_MenuMusic_blob (*(mui_MenuMusic_t*)&mui_MenuMusic)

typedef union {
    unsigned char raw[3];
    struct {
        struct { unsigned char _0_1_, _1_1_, _2_1_; };
    };
} spi_id_t;
#define spi_id_blob (*(spi_id_t*)&spi_id)

typedef union {
    unsigned char raw[304];
    struct {
        union { struct { unsigned char _0_1_, _1_1_, _2_1_, _3_1_; }; unsigned int _0_4_; };
        union { struct { unsigned char _4_1_, _5_1_, _6_1_, _7_1_; }; unsigned int _4_4_; };
        union { struct { unsigned char _8_1_, _9_1_, _10_1_, _11_1_; }; unsigned int _8_4_; };
        union { struct { unsigned char _12_1_, _13_1_, _14_1_, _15_1_; }; unsigned int _12_4_; };
        union { struct { unsigned char _16_1_, _17_1_, _18_1_, _19_1_; }; unsigned int _16_4_; };
        union { struct { unsigned char _20_1_, _21_1_, _22_1_, _23_1_; }; unsigned int _20_4_; };
        union { struct { unsigned char _24_1_, _25_1_, _26_1_, _27_1_; }; unsigned int _24_4_; };
        union { struct { unsigned char _28_1_, _29_1_, _30_1_, _31_1_; }; unsigned int _28_4_; };
        union { struct { unsigned char _32_1_, _33_1_, _34_1_, _35_1_; }; unsigned int _32_4_; };
        union { struct { unsigned char _36_1_, _37_1_, _38_1_, _39_1_; }; unsigned int _36_4_; };
        union { struct { unsigned char _40_1_, _41_1_, _42_1_, _43_1_; }; unsigned int _40_4_; };
        union { struct { unsigned char _44_1_, _45_1_, _46_1_, _47_1_; }; unsigned int _44_4_; };
        union { struct { unsigned char _48_1_, _49_1_, _50_1_, _51_1_; }; unsigned int _48_4_; };
        union { struct { unsigned char _52_1_, _53_1_, _54_1_, _55_1_; }; unsigned int _52_4_; };
        union { struct { unsigned char _56_1_, _57_1_, _58_1_, _59_1_; }; unsigned int _56_4_; };
        union { struct { unsigned char _60_1_, _61_1_, _62_1_, _63_1_; }; unsigned int _60_4_; };
        union { struct { unsigned char _64_1_, _65_1_, _66_1_, _67_1_; }; unsigned int _64_4_; };
        union { struct { unsigned char _68_1_, _69_1_, _70_1_, _71_1_; }; unsigned int _68_4_; };
        union { struct { unsigned char _72_1_, _73_1_, _74_1_, _75_1_; }; unsigned int _72_4_; };
        union { struct { unsigned char _76_1_, _77_1_, _78_1_, _79_1_; }; unsigned int _76_4_; };
        union { struct { unsigned char _80_1_, _81_1_, _82_1_, _83_1_; }; unsigned int _80_4_; };
        union { struct { unsigned char _84_1_, _85_1_, _86_1_, _87_1_; }; unsigned int _84_4_; };
        union { struct { unsigned char _88_1_, _89_1_, _90_1_, _91_1_; }; unsigned int _88_4_; };
        union { struct { unsigned char _92_1_, _93_1_, _94_1_, _95_1_; }; unsigned int _92_4_; };
        union { struct { unsigned char _96_1_, _97_1_, _98_1_, _99_1_; }; unsigned int _96_4_; };
        union { struct { unsigned char _100_1_, _101_1_, _102_1_, _103_1_; }; unsigned int _100_4_; };
        union { struct { unsigned char _104_1_, _105_1_, _106_1_, _107_1_; }; unsigned int _104_4_; };
        union { struct { unsigned char _108_1_, _109_1_, _110_1_, _111_1_; }; unsigned int _108_4_; };
        union { struct { unsigned char _112_1_, _113_1_, _114_1_, _115_1_; }; unsigned int _112_4_; };
        union { struct { unsigned char _116_1_, _117_1_, _118_1_, _119_1_; }; unsigned int _116_4_; };
        union { struct { unsigned char _120_1_, _121_1_, _122_1_, _123_1_; }; unsigned int _120_4_; };
        union { struct { unsigned char _124_1_, _125_1_, _126_1_, _127_1_; }; unsigned int _124_4_; };
        union { struct { unsigned char _128_1_, _129_1_, _130_1_, _131_1_; }; unsigned int _128_4_; };
        union { struct { unsigned char _132_1_, _133_1_, _134_1_, _135_1_; }; unsigned int _132_4_; };
        union { struct { unsigned char _136_1_, _137_1_, _138_1_, _139_1_; }; unsigned int _136_4_; };
        union { struct { unsigned char _140_1_, _141_1_, _142_1_, _143_1_; }; unsigned int _140_4_; };
        union { struct { unsigned char _144_1_, _145_1_, _146_1_, _147_1_; }; unsigned int _144_4_; };
        union { struct { unsigned char _148_1_, _149_1_, _150_1_, _151_1_; }; unsigned int _148_4_; };
        union { struct { unsigned char _152_1_, _153_1_, _154_1_, _155_1_; }; unsigned int _152_4_; };
        union { struct { unsigned char _156_1_, _157_1_, _158_1_, _159_1_; }; unsigned int _156_4_; };
        union { struct { unsigned char _160_1_, _161_1_, _162_1_, _163_1_; }; unsigned int _160_4_; };
        union { struct { unsigned char _164_1_, _165_1_, _166_1_, _167_1_; }; unsigned int _164_4_; };
        union { struct { unsigned char _168_1_, _169_1_, _170_1_, _171_1_; }; unsigned int _168_4_; };
        union { struct { unsigned char _172_1_, _173_1_, _174_1_, _175_1_; }; unsigned int _172_4_; };
        union { struct { unsigned char _176_1_, _177_1_, _178_1_, _179_1_; }; unsigned int _176_4_; };
        union { struct { unsigned char _180_1_, _181_1_, _182_1_, _183_1_; }; unsigned int _180_4_; };
        union { struct { unsigned char _184_1_, _185_1_, _186_1_, _187_1_; }; unsigned int _184_4_; };
        union { struct { unsigned char _188_1_, _189_1_, _190_1_, _191_1_; }; unsigned int _188_4_; };
        union { struct { unsigned char _192_1_, _193_1_, _194_1_, _195_1_; }; unsigned int _192_4_; };
        union { struct { unsigned char _196_1_, _197_1_, _198_1_, _199_1_; }; unsigned int _196_4_; };
        union { struct { unsigned char _200_1_, _201_1_, _202_1_, _203_1_; }; unsigned int _200_4_; };
        union { struct { unsigned char _204_1_, _205_1_, _206_1_, _207_1_; }; unsigned int _204_4_; };
        union { struct { unsigned char _208_1_, _209_1_, _210_1_, _211_1_; }; unsigned int _208_4_; };
        union { struct { unsigned char _212_1_, _213_1_, _214_1_, _215_1_; }; unsigned int _212_4_; };
        union { struct { unsigned char _216_1_, _217_1_, _218_1_, _219_1_; }; unsigned int _216_4_; };
        union { struct { unsigned char _220_1_, _221_1_, _222_1_, _223_1_; }; unsigned int _220_4_; };
        union { struct { unsigned char _224_1_, _225_1_, _226_1_, _227_1_; }; unsigned int _224_4_; };
        union { struct { unsigned char _228_1_, _229_1_, _230_1_, _231_1_; }; unsigned int _228_4_; };
        union { struct { unsigned char _232_1_, _233_1_, _234_1_, _235_1_; }; unsigned int _232_4_; };
        union { struct { unsigned char _236_1_, _237_1_, _238_1_, _239_1_; }; unsigned int _236_4_; };
        union { struct { unsigned char _240_1_, _241_1_, _242_1_, _243_1_; }; unsigned int _240_4_; };
        union { struct { unsigned char _244_1_, _245_1_, _246_1_, _247_1_; }; unsigned int _244_4_; };
        union { struct { unsigned char _248_1_, _249_1_, _250_1_, _251_1_; }; unsigned int _248_4_; };
        union { struct { unsigned char _252_1_, _253_1_, _254_1_, _255_1_; }; unsigned int _252_4_; };
        union { struct { unsigned char _256_1_, _257_1_, _258_1_, _259_1_; }; unsigned int _256_4_; };
        union { struct { unsigned char _260_1_, _261_1_, _262_1_, _263_1_; }; unsigned int _260_4_; };
        union { struct { unsigned char _264_1_, _265_1_, _266_1_, _267_1_; }; unsigned int _264_4_; };
        union { struct { unsigned char _268_1_, _269_1_, _270_1_, _271_1_; }; unsigned int _268_4_; };
        union { struct { unsigned char _272_1_, _273_1_, _274_1_, _275_1_; }; unsigned int _272_4_; };
        union { struct { unsigned char _276_1_, _277_1_, _278_1_, _279_1_; }; unsigned int _276_4_; };
        union { struct { unsigned char _280_1_, _281_1_, _282_1_, _283_1_; }; unsigned int _280_4_; };
        union { struct { unsigned char _284_1_, _285_1_, _286_1_, _287_1_; }; unsigned int _284_4_; };
        union { struct { unsigned char _288_1_, _289_1_, _290_1_, _291_1_; }; unsigned int _288_4_; };
        union { struct { unsigned char _292_1_, _293_1_, _294_1_, _295_1_; }; unsigned int _292_4_; };
        union { struct { unsigned char _296_1_, _297_1_, _298_1_, _299_1_; }; unsigned int _296_4_; };
        union { struct { unsigned char _300_1_, _301_1_, _302_1_, _303_1_; }; unsigned int _300_4_; };
    };
} ze_t;
#define ze_blob (*(ze_t*)&ze)

#endif
