/* proto.h — 函数原型（反编译签名行） */
#ifndef RK_PROTO_H
#define RK_PROTO_H
#include "ghidra_compat.h"
#include "globals.h"

extern gh_u4 main(void);
extern void RARCH_LOG(gh_u4 param_1);
extern void GetConfig(void);
extern int get_executable_path(char *param_1,char *param_2,size_t param_3);
extern void dispmeninfo(void);
extern void outputxy1(gh_byte *param_1);
extern void spi_printf(char *param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern gh_u4 ShareMemCreat(void);
extern gh_u4 ShareMemClose(void);
extern void xintiao(void);
extern void XintiaoThread(void);
extern gh_u4 UpdateROMProc(int param_1,int param_2);
extern void DateToTmuDate(gh_uint param_1);
extern void UpdateROM(char *param_1);
extern void TestUSBJoy(void);
extern void GetTick(void);
extern void WaitNMI(void);
extern void TestRun(void);
extern gh_u4 TestLibz0(void);
extern void TestLibz1(void);
extern void sunxi_gpio_init(void);
extern gh_u4 sunxi_gpio_set_cfgpin(int param_1,int param_2);
extern gh_uint sunxi_gpio_get_cfgpin(gh_uint param_1);
extern gh_u4 sunxi_gpio_output(int param_1,int param_2);
extern gh_uint sunxi_gpio_input(gh_uint param_1);
extern void sunxi_gpio_cleanup(void);
extern char get_from_line(char *param_1,int param_2);
extern gh_u4 GetInputInfo(char *param_1,gh_u4 param_2);
extern gh_uint ReadUSBJoy(int param_1);
extern void InitMDJoystick(void);
extern void ReadPS2JS(gh_uint param_1,gh_byte *param_2,gh_byte *param_3);
extern void ReadJoystickProc(void);
extern void processvblank(void);
extern void ReadJoystickThread(void);
extern void timer_thread(void);
extern void SetBacklight(int param_1);
extern void InitIOSignal(void);
extern void OutputIOSignal(void);
extern gh_u4 ReadJoystick(void);
extern void osDelay(int param_1);
extern void SPI_WW(gh_uint param_1);
extern gh_uint SPI_RR(void);
extern gh_u4 SPI_Read(gh_u4 param_1);
extern void SPI_Read_BUF(gh_u4 param_1,int param_2,int param_3);
extern void SPI_Write_BUF(gh_u4 param_1,int param_2,int param_3);
extern void SPI_Write(gh_u4 param_1,gh_u4 param_2);
extern void RxMode(void);
extern void TxMode(void);
extern int getticks(void);
extern void RF_Joystick_timer_isr(void);
extern void InitRFJoystick(void);
extern void InitJoystick(void);
extern gh_u4 GetDecodeData(void);
extern void InitDecode(void);
extern void ReInitDecode(void);
extern gh_u4 ScaleDisplayThread(void);
extern gh_u4 InitDisplay(void);
extern void dispFlip(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern void video_driver_set_rotation(gh_u4 param_1);
extern void video_driver_set_colormode(gh_u4 param_1);
extern void DeinitDisplay(void);
extern void InitSound(void);
extern void DeinitSound(void);
extern void PlaySound(void);
extern gh_uint ucrc32(gh_uint param_1,gh_byte *param_2,gh_uint param_3);
extern gh_u4 OpenZipU(void *param_1,gh_uint param_2,gh_uint param_3);
extern gh_u4 UnzipItem(int *param_1,int param_2,void *param_3,gh_uint param_4,gh_uint param_5);
extern gh_u4 CloseZipU(int *param_1);
extern void DrawSelectBar(int *param_1);
extern void mui_blockcopy(int *param_1,int *param_2);
extern void UnDrawSelectBar(int *param_1,int param_2,int param_3);
extern void mui_DispBlock(int param_1,int param_2,int param_3,int param_4);
extern void mui_UnDispBlock(int param_1,int param_2,int *param_3,int param_4);
extern void mui_Undisplay(int param_1,int param_2,int param_3,int param_4);
extern void mui_extract_basepath(char *param_1,char *param_2,int param_3);
extern void mui_extract_basename(char *param_1,char *param_2,int param_3);
extern void mui_DisplayThumbnail(void);
extern long buttontoi(char *param_1);
extern gh_byte strupr(gh_byte *param_1);
extern gh_u4 FilePreEmu(char *param_1);
extern gh_u1 GetWorkPath(void);
extern void mui_LoadSetting(void);
extern gh_u4 mui_LoadUIResource(gh_u4 *param_1,gh_u4 param_2);
extern void shoucang(char *param_1);
extern gh_u4 IsShoucang(char *param_1);
extern int mui_do_file_list(int param_1,gh_byte *param_2);
extern int mui_type_file_list(int param_1,gh_byte *param_2);
extern int mui_search_file_list(int param_1,int param_2);
extern int GetTicks(void);
extern void mui_DisplayThumbnailThread(void);
extern void mui_WaitNMI(void);
extern int mui_outputxy_t(int param_1,int param_2,int param_3,int param_4,gh_uint param_5,gh_byte *param_6);
extern void mui_DisplayGameSum(void);
extern void mui_DisplayLine_t(int param_1,int param_2,int param_3);
extern void mui_DisplayInputBuffer(void);
extern void mui_InitFont(void);
extern char strtrimr(char *param_1);
extern gh_byte strtriml(gh_byte *param_1);
extern void strtrim(void);
extern char get_item_from_line(gh_u4 param_1,char *param_2);
extern int get_items_from_file(char *param_1,int param_2);
extern int get_items_from_zipfile(gh_u4 param_1,int param_2);
extern char get_value_from_items(char *param_1,char *param_2,char *param_3,int param_4);
extern void mui_LoadConfig(void);
extern void gameType(void);
extern void LoadMenuLog(void);
extern void SaveMenuLog(void);
extern gh_uint mui_ReadJoystick(void);
extern int dir_serial_list(int param_1);
extern void outputblankxy(int param_1,int param_2,int param_3,int param_4);
extern void DisplayLine_list(gh_u4 param_1,int param_2,int param_3);
extern void DisplayPage_list(int param_1,gh_u4 param_2,int param_3);
extern char myStrrstr(char *param_1,char *param_2);
extern void EmuCore_Blank(int param_1,int param_2,int param_3,int param_4);
extern void EmuCore_Line(int param_1,int param_2,int param_3);
extern void EmuCore_list(int param_1,gh_u4 param_2,int param_3);
extern int SeletEmuCore(gh_u4 param_1);
extern gh_u4 GetFileCore(char *param_1);
extern gh_u4 ui_GetVolume(void);
extern void SoundClose(int param_1);
extern void ui_deinit(void);
extern void SoundPlay(int param_1,int *param_2);
extern gh_u4 filelist_run_game(char *param_1);
extern gh_u4 mui_run_game(char *param_1);
extern void mui_menu(void);
extern void mui_type(void);
extern void mui_search(void);
extern gh_u4 Mp3DecodeLoop(int param_1);
extern void AudioProcess(void);
extern void mui_SoundplayThread(void);
extern void LoadDefaultState(void);
extern void SaveDefaultState(void);
extern void InitKeyMapping0fEmuType(void);
extern void SaveKeyMappingConfigFile(void);
extern void blockadaptive(int *param_1,int *param_2);
extern void popwindows(gh_u4 *param_1);
extern void popoffwindows(gh_u4 *param_1);
extern void mui_recent(void);
extern void mui_shoucang(void);
extern void blockcopy(int *param_1,int *param_2);
extern void draw_state_select(int param_1,int param_2,int param_3);
extern void progress(char *param_1,gh_u4 param_2);
extern void spi_memcpy(void);
extern void InitScr(void);
extern gh_u4 GetJoystickConfig(int param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern void JoystickTest(int param_1);
extern void mui_setting(void);
extern void main_Menu(void);
extern gh_u4 mui_joystick_setting(void);
extern gh_u4 mui_video_setting(void);
extern gh_u4 mui_load_state(void);
extern gh_u4 mui_save_state(void);
extern gh_u4 mui_game_exit(void);
extern gh_u4 PauseMenu(void);
extern void joystick_poll(void);
extern gh_u4 PlayFrame(gh_u4 param_1,gh_u4 param_2);
extern gh_u4 gpsp_unzip(gh_u4 param_1,gh_u4 param_2);
extern void log_dummy(gh_uint param_1,gh_u4 param_2);
extern gh_bool joystick_input(gh_uint param_1,gh_u4 param_2,gh_u4 param_3,int param_4);
extern gh_u4 environment(int param_1,gh_uint *param_2);
extern void UIDebug(int param_1,int param_2,gh_u4 param_3,gh_uint param_4);
extern void DrawFrame(gh_u2 *param_1,int param_2,int param_3,int param_4);
extern void rgb8888_to_rgb565(gh_ushort *param_1,int param_2,int param_3);
extern int GetCoreIndex(char *param_1);
extern char GetFilenameExt(char *param_1);
extern void extract_basepath(char *param_1,char *param_2,int param_3);
extern void init_user_joy_key_mask(int param_1,gh_u4 param_2);
extern void TurboKeyProcess(void);
extern gh_u4 run_process(gh_u4 param_1,int param_2);
extern void RetroInitSound(void);
extern gh_bool Load_Proc1(char *param_1);
extern void Load_Proc2(void);
extern gh_u4 Snes_Load(char *param_1,int param_2);
extern gh_u4 TGB_Load(char *param_1,int param_2);
extern gh_u4 prosystem_Load(char *param_1,int param_2);
extern gh_u4 stella_Load(char *param_1,int param_2);
extern gh_u4 PCSX_Load(char *param_1);
extern gh_u4 FBA_Load(char *param_1);
extern gh_u4 Core_Load(char *param_1,gh_u4 param_2);
extern gh_u4 Gpsp_Load(char *param_1,int param_2);
extern gh_u4 run_game(char *param_1);
extern void autorun(gh_u4 param_1,char *param_2);
extern gh_u4 NES_Load(char *param_1,int param_2);
extern gh_u4 GBC_Load(char *param_1,int param_2);
extern gh_u4 VRT_Load(char *param_1,int param_2);
extern gh_u4 Pico_Load(char *param_1,int param_2);
extern gh_u4 retro_save_state(char *param_1);
extern gh_u4 retro_load_state(char *param_1);
extern gh_u4 MP3GetNextFrameInfo(int param_1,gh_u4 param_2,gh_u4 param_3);
extern void Convert_Stereo(gh_u2 *param_1);
extern void Convert_Mono(gh_u2 *param_1);
extern void ClearBuffer(gh_u1 *param_1,int param_2);
extern gh_uint sfc_request(gh_uint *param_1,gh_uint param_2,gh_uint *param_3,gh_uint param_4);
extern int snor_wait_busy(int param_1);
extern void snor_write_en(void);
extern void spi_write(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern void erase_sector(gh_u4 param_1);
extern void spi_read(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern void sflash_write_security_data(gh_u4 param_1,gh_u4 param_2);
extern void sflash_erase_security_data(gh_u4 param_1);
extern void sflash_read_security_data(gh_u4 param_1,gh_u4 param_2);
extern gh_u4 spi_driver_init(void);
extern gh_u4 sfc_uninit(void);
extern gh_u4 sfc_init(void);
extern gh_uint utf7_reset(int param_1,char *param_2,gh_uint param_3);
extern gh_bool normal_flushwc(int param_1,int *param_2);
extern gh_u4 hz_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern void uc_to_mb_write_replacement(void *param_1,gh_uint param_2,int *param_3);
extern void wc_to_mb_write_replacement(void *param_1,gh_uint param_2,int *param_3);
extern int compare_by_index(int param_1,int param_2);
extern int compare_by_name(gh_u4 *param_1,gh_u4 *param_2);
extern char locale_charset(void);
extern void __libc_csu_fini(void);

#endif