/* proto.h — 函数原型（反编译签名行） */
#ifndef RK_PROTO_H
#define RK_PROTO_H
#include "ghidra_compat.h"
#include "globals.h"

extern void _mxml_fini(void);
extern gh_u4 main(void);
extern void _start(gh_u4 param_1,gh_u4 param_2);
extern void call_weak_fn(void);
extern void deregister_tm_clones(void);
extern void register_tm_clones(void);
extern void __do_global_dtors_aux(void);
extern void frame_dummy(void);
extern void RARCH_LOG_V(char *param_1,__gnuc_va_list param_2);
extern void RARCH_LOG(gh_u4 param_1);
extern void GetConfig(void);
extern int get_executable_path(char *param_1,char *param_2,size_t param_3);
extern void dispmeninfo(void);
extern void outputxy1(gh_byte *param_1);
extern void spi_printf(char *param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern gh_u4 ShareMemCreat(void);
extern gh_u4 ShareMemClose(void);
extern void xintiao(void);
extern void XintiaoThread(void);
extern gh_u4 UpdateROMProc(int param_1,int param_2);
extern void DateToTmuDate(gh_uint param_1);
extern void UpdateROM(char *param_1);
extern void TestUSBJoy(void);
extern void GetTick(void);
extern void WaitNMI(void);
extern void TestRun(void);
extern gh_u4 TestLibz0(void);
extern void TestLibz1(void);
extern void sunxi_gpio_init(void);
extern gh_u4 sunxi_gpio_set_cfgpin(int param_1,int param_2);
extern gh_uint sunxi_gpio_get_cfgpin(gh_uint param_1);
extern gh_u4 sunxi_gpio_output(int param_1,int param_2);
extern gh_uint sunxi_gpio_input(gh_uint param_1);
extern void sunxi_gpio_cleanup(void);
extern char get_from_line(char *param_1,int param_2);
extern gh_u4 GetInputInfo(char *param_1,gh_u4 param_2);
extern gh_uint ReadUSBJoy(int param_1);
extern void InitMDJoystick(void);
extern void ReadPS2JS(gh_uint param_1,gh_byte *param_2,gh_byte *param_3);
extern void ReadJoystickProc(void);
extern void processvblank(void);
extern void ReadJoystickThread(void);
extern void timer_thread(void);
extern void SetBacklight(int param_1);
extern void InitIOSignal(void);
extern void OutputIOSignal(void);
extern gh_u4 ReadJoystick(void);
extern void osDelay(int param_1);
extern void SPI_WW(gh_uint param_1);
extern gh_uint SPI_RR(void);
extern gh_u4 SPI_Read(gh_u4 param_1);
extern void SPI_Read_BUF(gh_u4 param_1,int param_2,int param_3);
extern void SPI_Write_BUF(gh_u4 param_1,int param_2,int param_3);
extern void SPI_Write(gh_u4 param_1,gh_u4 param_2);
extern void RxMode(void);
extern void TxMode(void);
extern int getticks(void);
extern void RF_Joystick_timer_isr(void);
extern void InitRFJoystick(void);
extern void InitJoystick(void);
extern gh_u4 GetDecodeData(void);
extern void InitDecode(void);
extern void ReInitDecode(void);
extern gh_u4 ScaleDisplayThread(void);
extern gh_u4 run_process_constprop_0(gh_u4 param_1);
extern gh_u4 InitDisplay(void);
extern void dispFlip(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern void video_driver_set_rotation(gh_u4 param_1);
extern void video_driver_set_colormode(gh_u4 param_1);
extern void DeinitDisplay(void);
extern void InitSound(void);
extern void DeinitSound(void);
extern void PlaySound(void);
extern void zcalloc(void *param_1,gh_uint param_2,gh_uint param_3);
extern void zcfree(void *param_1,void *param_2);
extern int inflate_flush(inflate_blocks_state *param_1,z_stream_s *param_2,int param_3);
extern void inflate_codes_free(inflate_codes_state *param_1,z_stream_s *param_2);
extern void inflate_blocks_reset(inflate_blocks_state *param_1,z_stream_s *param_2,gh_ulong *param_3);
extern gh_u4 inflate_blocks_free(inflate_blocks_state *param_1,z_stream_s *param_2);
extern void inflate_codes(inflate_blocks_state *param_1,z_stream_s *param_2,int param_3);
extern void inflate_blocks(inflate_blocks_state *param_1,z_stream_s *param_2,int param_3);
extern gh_u1 get_crc_table(void);
extern gh_uint ucrc32(gh_uint param_1,gh_byte *param_2,gh_uint param_3);
extern gh_uint adler32(gh_ulong param_1,gh_uchar *param_2,gh_uint param_3);
extern char zlibVersion(void);
extern gh_undef zError(int param_1);
extern gh_u4 inflateReset(z_stream_s *param_1);
extern gh_u4 inflateEnd(z_stream_s *param_1);
extern gh_u4 inflateInit2(z_stream_s *param_1);
extern int inflate(z_stream_s *param_1,int param_2);
extern gh_u1 lufopen(void *param_1,gh_uint param_2,gh_uint param_3,gh_uint *param_4);
extern gh_u4 lufclose(LUFILE *param_1);
extern bool luferror(LUFILE *param_1);
extern int luftell(LUFILE *param_1);
extern int lufseek(LUFILE *param_1,long param_2,int param_3);
extern void lufread(void *param_1,gh_uint param_2,gh_uint param_3,LUFILE *param_4);
extern int unzlocal_getByte(LUFILE *param_1,int *param_2);
extern void unzlocal_getShort(LUFILE *param_1,gh_ulong *param_2);
extern void unzlocal_getLong(LUFILE *param_1,gh_ulong *param_2);
extern int strcmpcasenosensitive_internal(char *param_1,char *param_2);
extern void unzStringFileNameCompare(char *param_1,char *param_2,int param_3);
extern int unzlocal_SearchCentralDir(LUFILE *param_1);
extern gh_u4 unzGetGlobalInfo(unz_s *param_1,unz_global_info_s *param_2);
extern void unzlocal_DosDateToTmuDate(gh_ulong param_1,tm_unz_s *param_2);
extern int unzGoToFirstFile(unz_s *param_1);
extern unz_s unzOpenInternal(LUFILE *param_1);
extern int unzGoToNextFile(unz_s *param_1);
extern int unzLocateFile(unz_s *param_1,char *param_2,int param_3);
extern int unzReadCurrentFile(unz_s *param_1,void *param_2,gh_uint param_3);
extern gh_u4 unztell(unz_s *param_1);
extern gh_uint unzeof(unz_s *param_1);
extern gh_uint unzGetLocalExtrafield(unz_s *param_1,void *param_2,gh_uint param_3);
extern gh_u4 unzCloseCurrentFile(unz_s *param_1);
extern gh_u4 unzClose(unz_s *param_1);
extern gh_u4 unzOpenCurrentFile(unz_s *param_1);
extern gh_uint unzGetGlobalComment(unz_s *param_1,char *param_2,gh_ulong param_3);
extern void timet2filetime(long param_1);
extern size_t FormatZipMessageU(gh_uint param_1,char *param_2,gh_uint param_3);
extern gh_u4 OpenZipU(void *param_1,gh_uint param_2,gh_uint param_3);
extern gh_u4 GetZipItemA(int *param_1,int param_2,ZIPENTRY *param_3);
extern int GetZipItemW(HZIP__ *param_1,int param_2,ZIPENTRYW *param_3);
extern gh_u4 FindZipItemA(int *param_1,char *param_2,gh_uchar param_3,int *param_4,ZIPENTRY *param_5);
extern int FindZipItemW(HZIP__ *param_1,char *param_2,gh_uchar param_3,int *param_4,ZIPENTRYW *param_5);
extern gh_u4 UnzipItem(int *param_1,int param_2,void *param_3,gh_uint param_4,gh_uint param_5);
extern gh_u4 CloseZipU(int *param_1);
extern bool IsZipHandleU(HZIP__ *param_1);
extern void stbtt__cff_get_index(int *param_1,int *param_2);
extern gh_uint stbtt__cff_int(int *param_1);
extern void stbtt__dict_get_ints(int *param_1,gh_uint param_2,int param_3,int param_4);
extern bool stbtt__isfont(char *param_1);
extern int stbtt__find_table(int param_1,int param_2,char *param_3);
extern gh_u4 stbtt__get_subrs(gh_u4 *param_1,int param_2,gh_u4 param_3,int param_4);
extern int stbtt__GetGlyfOffset(int param_1,int param_2);
extern void stbtt__track_vertex(int param_1,int param_2,int param_3);
extern void stbtt__csctx_close_shape(int param_1);
extern void stbtt__csctx_rmove_to(int param_1);
extern void stbtt__csctx_rline_to(float param_1,float param_2,int param_3);
extern void stbtt__sort_edges_quicksort(gh_u4 *param_1,int param_2);
extern int stbtt__CompareUTF8toUTF16_bigendian_prefix(int param_1,int param_2,gh_byte *param_3,int param_4);
extern bool stbtt__matchpair(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6);
extern void DrawSelectBar(int *param_1);
extern void mui_blockcopy(int *param_1,int *param_2);
extern void UnDrawSelectBar(int *param_1,int param_2,int param_3);
extern void mui_DispBlock(int param_1,int param_2,int param_3,int param_4);
extern void mui_UnDispBlock(int param_1,int param_2,int *param_3,int param_4);
extern void mui_Undisplay(int param_1,int param_2,int param_3,int param_4);
extern void stbtt__h_prefilter(int param_1,gh_uint param_2,int param_3,int param_4,size_t param_5);
extern void stbtt__v_prefilter(int param_1,int param_2,gh_uint param_3,int param_4,size_t param_5);
extern void mui_extract_basepath(char *param_1,char *param_2,int param_3);
extern void mui_extract_basename(char *param_1,char *param_2,int param_3);
extern void mui_DisplayThumbnail(void);
extern long buttontoi(char *param_1);
extern void stbtt__cff_index_get_isra_2(gh_u4 *param_1,gh_u1 *param_2,gh_uint param_3,int param_4);
extern gh_u4 stbtt__run_charstring(int param_1,int param_2,gh_u4 param_3);
extern int stbtt__GetGlyphClass(gh_byte *param_1,int param_2);
extern float stbtt__cuberoot(float param_1);
extern int code_convert_constprop_22(gh_u4 param_1,gh_u4 param_2,void *param_3,size_t param_4);
extern gh_byte strupr(gh_byte *param_1);
extern gh_u4 FilePreEmu(char *param_1);
extern gh_u1 GetWorkPath(void);
extern void mui_LoadSetting(void);
extern gh_u4 mui_LoadUIResource(gh_u4 *param_1,gh_u4 param_2);
extern void shoucang(char *param_1);
extern gh_u4 IsShoucang(char *param_1);
extern int mui_do_file_list(int param_1,gh_byte *param_2);
extern int mui_type_file_list(int param_1,gh_byte *param_2);
extern int mui_search_file_list(int param_1,int param_2);
extern int GetTicks(void);
extern void mui_DisplayThumbnailThread(void);
extern void mui_WaitNMI(void);
extern gh_uint stbtt_FindGlyphIndex(int param_1,gh_uint param_2);
extern bool stbtt_IsGlyphEmpty(int param_1,gh_u4 param_2);
extern void stbtt_GetGlyphShape(int param_1,gh_u4 param_2,gh_u4 *param_3);
extern void stbtt_GetCodepointShape(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern void stbtt_GetGlyphHMetrics(int param_1,int param_2,int *param_3,int *param_4);
extern int stbtt_GetGlyphKernAdvance(int param_1,int param_2,gh_uint param_3);
extern gh_u4 stbtt_GetCodepointKernAdvance(int param_1,gh_u4 param_2,gh_u4 param_3);
extern void stbtt_GetFontVMetrics(int param_1,int *param_2,int *param_3,int *param_4);
extern gh_u4 stbtt_GetFontVMetricsOS2(int param_1,int *param_2,int *param_3,int *param_4);
extern void stbtt_GetFontBoundingBox(int param_1,int *param_2,int *param_3,int *param_4,int *param_5);
extern float stbtt_ScaleForPixelHeight(float param_1,int param_2);
extern float stbtt_ScaleForMappingEmToPixels(float param_1,int param_2);
extern void stbtt_FreeShape(gh_u4 param_1,void *param_2);
extern void stbtt_GetGlyphBitmapBox(gh_u4 param_1,gh_u4 param_2);
extern int mui_outputxy_length_isra_19(int param_1,int param_2,gh_byte *param_3);
extern void stbtt_GetCodepointBitmapBox(gh_u4 param_1,gh_u4 param_2);
extern void stbtt_FreeBitmap(void *param_1);
extern void stbtt_GetGlyphBitmap(gh_u4 param_1,gh_u4 param_2);
extern void stbtt_MakeGlyphBitmap(gh_u4 param_1,gh_u4 param_2);
extern int mui_outputxy_t(int param_1,int param_2,int param_3,int param_4,gh_uint param_5,gh_byte *param_6);
extern void mui_DisplayGameSum(void);
extern void mui_DisplayLine_t(int param_1,int param_2,int param_3);
extern void mui_DisplayInputBuffer(void);
extern void stbtt_GetCodepointBitmap(gh_u4 param_1,gh_u4 param_2);
extern void stbtt_MakeCodepointBitmap(gh_u4 param_1,gh_u4 param_2);
extern void stbtt_PackEnd(int param_1);
extern void stbtt_PackSetOversampling(int param_1,gh_uint param_2,gh_uint param_3);
extern void stbtt_PackSetSkipMissingCodepoints(int param_1,gh_u4 param_2);
extern void stbtt_PackFontRangesPackRects(int param_1,int *param_2,int param_3);
extern void stbtt_FreeSDF(void *param_1);
extern int stbtt_GetFontOffsetForIndex(char *param_1);
extern int stbtt_GetNumberOfFonts(gh_u4 param_1);
extern gh_u4 stbtt_InitFont(int param_1,int param_2,gh_u4 param_3);
extern void stbtt_PackFontRange(void);
extern void mui_InitFont(void);
extern int stbtt_FindMatchingFont(int param_1,char *param_2,gh_uint param_3);
extern bool stbtt_CompareUTF8toUTF16_bigendian(void);
extern char strtrimr(char *param_1);
extern gh_byte strtriml(gh_byte *param_1);
extern void strtrim(void);
extern char get_item_from_line(gh_u4 param_1,char *param_2);
extern int get_items_from_file(char *param_1,int param_2);
extern int get_items_from_zipfile(gh_u4 param_1,int param_2);
extern char get_value_from_items(char *param_1,char *param_2,char *param_3,int param_4);
extern void mui_LoadConfig(void);
extern void gameType(void);
extern void LoadMenuLog(void);
extern void SaveMenuLog(void);
extern gh_uint mui_ReadJoystick(void);
extern int dir_serial_list(int param_1);
extern void outputblankxy(int param_1,int param_2,int param_3,int param_4);
extern void DisplayLine_list(gh_u4 param_1,int param_2,int param_3);
extern void DisplayPage_list(int param_1,gh_u4 param_2,int param_3);
extern char myStrrstr(char *param_1,char *param_2);
extern void EmuCore_Blank(int param_1,int param_2,int param_3,int param_4);
extern void EmuCore_Line(int param_1,int param_2,int param_3);
extern void EmuCore_list(int param_1,gh_u4 param_2,int param_3);
extern int SeletEmuCore(gh_u4 param_1);
extern gh_u4 GetFileCore(char *param_1);
extern gh_u4 ui_GetVolume(void);
extern void SoundClose(int param_1);
extern void ui_deinit(void);
extern void SoundPlay(int param_1,int *param_2);
extern gh_u4 filelist_run_game(char *param_1);
extern gh_u4 mui_run_game(char *param_1);
extern void mui_menu(void);
extern void mui_type(void);
extern void mui_search(void);
extern gh_u4 Mp3DecodeLoop(int param_1);
extern void AudioProcess(void);
extern void mui_SoundplayThread(void);
extern void LoadDefaultState(void);
extern void SaveDefaultState(void);
extern void InitKeyMapping0fEmuType(void);
extern void SaveKeyMappingConfigFile(void);
extern void blockadaptive(int *param_1,int *param_2);
extern void popwindows(gh_u4 *param_1);
extern void popoffwindows(gh_u4 *param_1);
extern void mui_recent(void);
extern void mui_shoucang(void);
extern void blockcopy(int *param_1,int *param_2);
extern void draw_state_select(int param_1,int param_2,int param_3);
extern void progress(char *param_1,gh_u4 param_2);
extern void spi_memcpy(void);
extern void InitScr(void);
extern gh_u4 GetJoystickConfig(int param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern void JoystickTest(int param_1);
extern void mui_setting(void);
extern void main_Menu(void);
extern gh_u4 mui_joystick_setting(void);
extern gh_u4 mui_video_setting(void);
extern gh_u4 mui_load_state(void);
extern gh_u4 mui_save_state(void);
extern gh_u4 mui_game_exit(void);
extern gh_u4 PauseMenu(void);
extern void FUN_00095132(void);
extern void __ErrorSoundEnd(void);
extern gh_u4 __SetTruboSoundEnd(gh_u4 param_1);
extern void joystick_poll(void);
extern gh_u4 PlayFrame(gh_u4 param_1,gh_u4 param_2);
extern gh_u4 gpsp_unzip(gh_u4 param_1,gh_u4 param_2);
extern void log_dummy(gh_uint param_1,gh_u4 param_2);
extern bool joystick_input(gh_uint param_1,gh_u4 param_2,gh_u4 param_3,int param_4);
extern gh_u4 environment(int param_1,gh_uint *param_2);
extern void UIDebug(int param_1,int param_2,gh_u4 param_3,gh_uint param_4);
extern void DrawFrame(gh_u2 *param_1,int param_2,int param_3,int param_4);
extern void rgb8888_to_rgb565(gh_ushort *param_1,int param_2,int param_3);
extern int GetCoreIndex(char *param_1);
extern char GetFilenameExt(char *param_1);
extern void extract_basepath(char *param_1,char *param_2,int param_3);
extern void init_user_joy_key_mask(int param_1,gh_u4 param_2);
extern void TurboKeyProcess(void);
extern gh_u4 run_process(gh_u4 param_1,int param_2);
extern void RetroInitSound(void);
extern bool Load_Proc1(char *param_1);
extern void Load_Proc2(void);
extern gh_u4 Snes_Load(char *param_1,int param_2);
extern gh_u4 TGB_Load(char *param_1,int param_2);
extern gh_u4 prosystem_Load(char *param_1,int param_2);
extern gh_u4 stella_Load(char *param_1,int param_2);
extern gh_u4 PCSX_Load(char *param_1);
extern gh_u4 FBA_Load(char *param_1);
extern gh_u4 Core_Load(char *param_1,gh_u4 param_2);
extern gh_u4 Gpsp_Load(char *param_1,int param_2);
extern gh_u4 run_game(char *param_1);
extern void autorun(gh_u4 param_1,char *param_2);
extern gh_u4 NES_Load(char *param_1,int param_2);
extern gh_u4 GBC_Load(char *param_1,int param_2);
extern gh_u4 VRT_Load(char *param_1,int param_2);
extern gh_u4 Pico_Load(char *param_1,int param_2);
extern gh_u4 retro_save_state(char *param_1);
extern gh_u4 retro_load_state(char *param_1);
extern void MP3FreeDecoder(int param_1);
extern int MP3FindSyncWord(gh_byte *param_1,int param_2);
extern void MP3GetLastFrameInfo(int param_1,gh_u4 *param_2);
extern gh_u4 MP3GetNextFrameInfo(int param_1,gh_u4 param_2,gh_u4 param_3);
extern gh_u4 MP3Decode(int param_1,int *param_2,int *param_3,int param_4,int param_5);
extern void Convert_Stereo(gh_u2 *param_1);
extern void Convert_Mono(gh_u2 *param_1);
extern void xmp3_MidSideProc(int param_1,int param_2,gh_uint *param_3);
extern gh_u4 xmp3_Subband(int param_1,int param_2);
extern void WinPrevious(int *param_1,int *param_2,int param_3);
extern gh_uint FreqInvertRescale(int param_1,int param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 xmp3_IMDCT(gh_u4 *param_1,int param_2,int param_3);
extern gh_uint DequantBlock(gh_uint *param_1,int param_2,int param_3,gh_uint param_4);
extern gh_u4 xmp3_Dequantize(gh_u4 *param_1,int param_2);
extern void xmp3_FDCT32(gh_uint *param_1,int param_2,int param_3,int param_4,int param_5);
extern void xmp3_SetBitstreamPointer(gh_u4 *param_1,gh_u4 param_2,gh_u4 param_3);
extern gh_uint xmp3_GetBits(gh_u4 *param_1,gh_uint param_2);
extern int xmp3_CalcBitsUsed(int *param_1,int param_2,int param_3);
extern gh_uint xmp3_CheckPadBit(int *param_1);
extern gh_u4 xmp3_UnpackFrameHeader(int *param_1,char *param_2);
extern gh_u4 xmp3_UnpackSideInfo(gh_u4 *param_1,gh_u4 param_2);
extern void ClearBuffer(gh_u1 *param_1,int param_2);
extern gh_u1 xmp3_AllocateBuffers(void);
extern void xmp3_FreeBuffers(void);
extern void xmp3_PolyphaseMono(gh_ushort *param_1,int *param_2,int *param_3);
extern void xmp3_PolyphaseStereo(gh_ushort *param_1,int *param_2,int *param_3);
extern gh_u4 mxml_set_attr(int param_1,char *param_2,gh_u4 param_3);
extern void mxmlElementDeleteAttr(int *param_1,char *param_2);
extern gh_u4 mxmlElementGetAttr(int *param_1,char *param_2);
extern void mxmlElementSetAttr(int *param_1,int param_2,int param_3);
extern void mxmlElementSetAttrf(int *param_1,int param_2,int param_3);
extern gh_u4 mxmlEntityAddCallback(gh_u4 param_1);
extern gh_undef mxmlEntityGetName(gh_u4 param_1);
extern int mxmlEntityGetValue(gh_u4 param_1);
extern void mxmlEntityRemoveCallback(int param_1);
extern gh_u4 _mxml_entity_cb(char *param_1);
extern gh_u4 mxml_string_putc(gh_u1 param_1,gh_u4 *param_2);
extern gh_uint mxml_string_getc(gh_u4 *param_1,int *param_2);
extern gh_uint mxml_get_entity(int param_1,gh_u4 param_2,gh_u4 param_3,gh_code *param_4);
extern gh_u4 mxml_add_char(gh_uint param_1,int *param_2,int *param_3,size_t *param_4);
extern gh_uint mxml_file_getc(_IO_FILE *param_1,int *param_2);
extern gh_u4 mxml_write_string(char *param_1,gh_u4 param_2,gh_code *param_3);
extern gh_u4 mxml_fd_write(int *param_1);
extern gh_u4 mxml_fd_putc(gh_u1 param_1,int param_2);
extern int mxml_file_putc(int param_1,_IO_FILE *param_2);
extern bool mxml_isspace_part_0(int param_1);
extern gh_u4 mxml_fd_read_part_1(int *param_1);
extern gh_uint mxml_fd_getc(int param_1,int *param_2);
extern int mxml_write_name(char *param_1,gh_u4 param_2,gh_code *param_3);
extern void mxmlLoadFd(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern void mxmlLoadFile(void);
extern void mxmlLoadString(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern gh_u4 mxmlSaveFd(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern int mxmlSaveFile(gh_u4 param_1,_IO_FILE *param_2,gh_u4 param_3);
extern int mxmlSaveString(gh_u4 param_1,gh_u1 *param_2,int param_3,gh_u4 param_4);
extern void mxmlSaveAllocString(gh_u4 param_1,gh_u4 param_2);
extern void mxmlSAXLoadFile(void);
extern void mxmlSetCustomHandlers(gh_u4 param_1,gh_u4 param_2);
extern void mxmlSetErrorCallback(gh_u4 param_1);
extern void mxmlSetWrapMargin(gh_u4 param_1);
extern char mxmlGetCDATA(int *param_1);
extern int mxmlGetCustom(int *param_1);
extern int mxmlGetElement(int *param_1);
extern int mxmlGetFirstChild(int *param_1);
extern int mxmlGetInteger(int *param_1);
extern int mxmlGetLastChild(int *param_1);
extern gh_u4 mxmlGetNextSibling(int param_1);
extern int mxmlGetOpaque(int *param_1);
extern gh_u4 mxmlGetParent(int param_1);
extern gh_u4 mxmlGetPrevSibling(int param_1);
extern gh_u4 mxmlGetReal(int *param_1);
extern int mxmlGetText(int *param_1,int *param_2);
extern gh_u4 mxmlGetType(gh_u4 *param_1);
extern gh_u4 mxmlGetUserData(int param_1);
extern int index_find_isra_0(gh_u4 *param_1,char *param_2,char *param_3,int param_4);
extern void index_compare_isra_2(int *param_1,int param_2,int param_3);
extern void index_sort(int param_1,int param_2,int param_3);
extern void mxmlIndexDelete(gh_u4 *param_1);
extern gh_u4 mxmlIndexEnum(int param_1);
extern gh_u4 mxmlIndexFind(int *param_1,int param_2,int param_3);
extern gh_u4 mxmlIndexGetCount(int param_1);
extern gh_u4 mxmlIndexNew(int param_1,int param_2,int param_3);
extern gh_u4 mxmlIndexReset(int param_1);
extern gh_u4 mxmlGetRefCount(int param_1);
extern void mxmlRemove(int param_1);
extern void mxmlAdd(int param_1,int param_2,int param_3,int param_4);
extern gh_u4 mxml_new(int param_1,gh_u4 param_2);
extern int mxmlNewCDATA(gh_u4 param_1,int param_2);
extern void mxmlNewCustom(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern int mxmlNewElement(gh_u4 param_1,int param_2);
extern void mxmlNewInteger(gh_u4 param_1,gh_u4 param_2);
extern int mxmlNewOpaque(gh_u4 param_1,int param_2);
extern void mxmlNewReal(gh_u4 param_1);
extern int mxmlNewText(gh_u4 param_1,gh_u4 param_2,int param_3);
extern int mxmlNewTextf(gh_u4 param_1,gh_u4 param_2,int param_3);
extern void mxmlDelete(gh_u4 *param_1);
extern void mxmlNewXML(gh_undef *param_1);
extern int mxmlRelease(int param_1);
extern void mxmlRetain(int param_1);
extern void _mxml_destructor(void *param_1);
extern void _mxml_init(void);
extern gh_u4 mxml_ignore_cb(void);
extern gh_u4 mxml_integer_cb(void);
extern gh_u4 mxml_opaque_cb(void);
extern gh_u4 mxml_real_cb(void);
extern void _mxml_global(void);
extern void mxml_error(char *param_1,gh_u4 param_2,gh_u4 param_3,gh_u4 param_4);
extern int mxmlWalkNext(int param_1,int param_2,int param_3);
extern int mxmlFindElement(int param_1,int param_2,char *param_3,int param_4,char *param_5,int param_6);
extern int mxmlFindPath(int *param_1,char *param_2);
extern int mxmlWalkPrev(int param_1,int param_2,int param_3);
extern gh_u4 mxmlSetCDATA(int *param_1,int param_2);
extern gh_u4 mxmlSetCustom(int *param_1,int param_2,int param_3);
extern gh_u4 mxmlSetElement(int *param_1,int param_2);
extern gh_u4 mxmlSetInteger(int *param_1,int param_2);
extern gh_u4 mxmlSetOpaque(int *param_1,int param_2);
extern gh_u4 mxmlSetReal(int *param_1);
extern gh_u4 mxmlSetText(int *param_1,int param_2,int param_3);
extern gh_u4 mxmlSetTextf(int *param_1,int param_2,int param_3);
extern gh_u4 mxmlSetUserData(int param_1,gh_u4 param_2);
extern char _mxml_vstrdupf(char *param_1,__gnuc_va_list param_2);
extern void _mxml_strdupf(gh_u4 param_1);
extern gh_uint sfc_request(gh_uint *param_1,gh_uint param_2,gh_uint *param_3,gh_uint param_4);
extern int snor_wait_busy(int param_1);
extern void snor_write_en(void);
extern void spi_write(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern void erase_sector(gh_u4 param_1);
extern void spi_read(gh_u4 param_1,gh_u4 param_2,gh_u4 param_3);
extern void sflash_write_security_data(gh_u4 param_1,gh_u4 param_2);
extern void sflash_erase_security_data(gh_u4 param_1);
extern void sflash_read_security_data(gh_u4 param_1,gh_u4 param_2);
extern gh_u4 spi_driver_init(void);
extern gh_u4 sfc_uninit(void);
extern gh_u4 sfc_init(void);
extern gh_u4 ascii_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 ascii_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 utf8_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint utf8_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_uint ucs2_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ucs2_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 ucs2be_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ucs2be_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 ucs2le_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ucs2le_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_uint ucs4_mbtowc(int param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ucs4_wctomb(gh_u4 param_1,gh_u1 *param_2,int param_3,gh_uint param_4);
extern gh_u4 ucs4be_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ucs4be_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 ucs4le_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ucs4le_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_uint utf16_mbtowc(int param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern int utf16_wctomb(int param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_u4 utf16be_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 utf16be_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_u4 utf16le_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 utf16le_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_uint utf32_mbtowc(int param_1,gh_u4 *param_2,gh_byte *param_3,gh_uint param_4);
extern int utf32_wctomb(int param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_u4 utf32be_mbtowc(gh_u4 param_1,gh_u4 *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 utf32be_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_u4 utf32le_mbtowc(gh_u4 param_1,gh_u4 *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 utf32le_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_uint utf7_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint utf7_wctomb(int param_1,char *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_uint utf7_reset(int param_1,char *param_2,gh_uint param_3);
extern gh_u4 ucs2internal_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_ushort *param_3,gh_uint param_4);
extern gh_u4 ucs2internal_wctomb(gh_u4 param_1,gh_u2 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 ucs2swapped_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_ushort *param_3,gh_uint param_4);
extern gh_u4 ucs2swapped_wctomb(gh_u4 param_1,gh_ushort *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 ucs4swapped_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_uint *param_3,gh_uint param_4);
extern gh_u4 ucs4swapped_wctomb(gh_u4 param_1,gh_uint *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 c99_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint c99_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 java_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 java_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_u4 iso8859_1_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_1_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 iso8859_2_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_2_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_3_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_3_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_4_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_4_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_5_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_5_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_6_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_6_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_7_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_7_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_8_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_8_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_9_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_9_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_10_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_10_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_11_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_11_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_13_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_13_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_14_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_14_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_15_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_15_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 iso8859_16_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso8859_16_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 koi8_r_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 koi8_r_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 koi8_u_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 koi8_u_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 koi8_ru_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 koi8_ru_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1250_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1250_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1251_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1251_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1252_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1252_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1253_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1253_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1254_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1254_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern bool normal_flushwc(int param_1,int *param_2);
extern gh_u4 cp1255_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1255_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 cp1256_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1256_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1257_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1257_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1258_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1258_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 cp850_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp850_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp862_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp862_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp866_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp866_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1131_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1131_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_roman_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_roman_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_centraleurope_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_centraleurope_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_iceland_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_iceland_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_croatian_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_croatian_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_romania_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_romania_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_cyrillic_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_cyrillic_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_ukraine_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_ukraine_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_greek_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_greek_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_turkish_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_turkish_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_hebrew_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_hebrew_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_arabic_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_arabic_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mac_thai_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mac_thai_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 hp_roman8_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 hp_roman8_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 nextstep_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 nextstep_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 armscii_8_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 armscii_8_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 georgian_academy_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 georgian_academy_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 georgian_ps_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 georgian_ps_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 koi8_t_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 koi8_t_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 pt154_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 pt154_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 rk1048_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 rk1048_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 mulelao_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 mulelao_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp1133_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp1133_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 tis620_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 tis620_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp874_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp874_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 viscii_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 viscii_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 tcvn_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 tcvn_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 iso646_jp_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso646_jp_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 jisx0201_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 jisx0201_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 jisx0208_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 jisx0208_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 jisx0212_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 jisx0212_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 iso646_cn_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 iso646_cn_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 gb2312_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 gb2312_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 isoir165ext_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 isoir165ext_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern int isoir165_mbtowc(gh_u4 param_1,gh_u4 param_2,char *param_3,gh_uint param_4);
extern gh_u4 isoir165_wctomb(gh_u4 param_1,gh_byte *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 gbkext1_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 gbkext2_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 gbkext_inv_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 cp936ext_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cp936ext_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern int gbk_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 gbk_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 cns11643_1_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_2_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_3_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_4_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_5_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_6_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_7_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_15_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cns11643_inv_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 big5_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 big5_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 ksc5601_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 ksc5601_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 johab_hangul_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 johab_hangul_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern int johab_hangul_decompose(gh_u4 param_1,int *param_2,gh_u4 param_3);
extern gh_u4 euc_jp_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern int euc_jp_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 sjis_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 sjis_wctomb(gh_u4 param_1,gh_byte *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 cp932ext_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cp932ext_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 cp932_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 cp932_wctomb(gh_u4 param_1,gh_byte *param_2,gh_uint param_3,gh_uint param_4);
extern gh_uint iso2022_jp_mbtowc(int param_1,gh_u4 param_2,char *param_3,gh_uint param_4);
extern gh_uint iso2022_jp_wctomb(int param_1,char *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 iso2022_jp_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_uint iso2022_jp1_mbtowc(int param_1,gh_u4 param_2,char *param_3,gh_uint param_4);
extern gh_uint iso2022_jp1_wctomb(int param_1,char *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 iso2022_jp1_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_uint iso2022_jp2_mbtowc(int param_1,int *param_2,char *param_3,gh_uint param_4);
extern gh_uint iso2022_jp2_wctomb(int param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 iso2022_jp2_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 cp50221_0208_ext_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp50221_0208_ext_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3);
extern gh_u4 cp50221_0212_ext_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3);
extern gh_u4 cp50221_0212_ext_wctomb(gh_u4 param_1,char *param_2,char *param_3);
extern gh_uint iso2022_jpms_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint iso2022_jpms_wctomb(int param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 iso2022_jpms_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 euc_cn_mbtowc(gh_u4 param_1,gh_u4 param_2,gh_byte *param_3,gh_uint param_4);
extern int euc_cn_wctomb(gh_u4 param_1,char *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 ces_gbk_mbtowc(gh_u4 param_1,gh_u4 param_2,gh_byte *param_3,gh_uint param_4);
extern int ces_gbk_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_u4 param_3,gh_uint param_4);
extern int cp936_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern int cp936_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 gb18030ext_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 gb18030ext_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 gb18030uni_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 gb18030uni_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern int gb18030_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern int gb18030_wctomb(gh_u4 param_1,char *param_2,gh_undef *param_3,gh_uint param_4);
extern gh_uint iso2022_cn_mbtowc(int param_1,int *param_2,char *param_3,gh_uint param_4);
extern gh_uint iso2022_cn_wctomb(int param_1,char *param_2,int param_3,gh_uint param_4);
extern gh_u4 iso2022_cn_reset(int param_1,gh_u1 *param_2,int param_3);
extern gh_uint iso2022_cn_ext_mbtowc(int param_1,int *param_2,char *param_3,gh_uint param_4);
extern gh_uint iso2022_cn_ext_wctomb(int param_1,char *param_2,int param_3,gh_uint param_4);
extern gh_u4 iso2022_cn_ext_reset(int param_1,gh_u1 *param_2,int param_3);
extern gh_uint hz_mbtowc(int param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint hz_wctomb(int param_1,char *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 hz_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 euc_tw_mbtowc(gh_u4 param_1,gh_u4 param_2,gh_byte *param_3,gh_uint param_4);
extern int euc_tw_wctomb(gh_u4 param_1,char *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 ces_big5_mbtowc(gh_u4 param_1,gh_u4 param_2,gh_byte *param_3,gh_uint param_4);
extern int ces_big5_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 cp950ext_mbtowc(gh_u4 param_1,gh_uint *param_2,char *param_3,gh_uint param_4);
extern gh_u4 cp950ext_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_undef *param_3,gh_uint param_4);
extern int cp950_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern int cp950_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 hkscs1999_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 hkscs1999_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern int big5hkscs1999_mbtowc(int param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint big5hkscs1999_wctomb(int param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 big5hkscs1999_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 hkscs2001_mbtowc(gh_u4 param_1,gh_uint *param_2,char *param_3,gh_uint param_4);
extern gh_u4 hkscs2001_wctomb(gh_u4 param_1,gh_u1 *param_2,word *param_3,gh_uint param_4);
extern int big5hkscs2001_mbtowc(int param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint big5hkscs2001_wctomb(int param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 big5hkscs2001_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 hkscs2004_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 hkscs2004_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_code *param_3,gh_uint param_4);
extern int big5hkscs2004_mbtowc(int param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint big5hkscs2004_wctomb(int param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 big5hkscs2004_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 hkscs2008_mbtowc(gh_u4 param_1,gh_uint *param_2,char *param_3,gh_uint param_4);
extern gh_u4 hkscs2008_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_code *param_3,gh_uint param_4);
extern int big5hkscs2008_mbtowc(int param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_uint big5hkscs2008_wctomb(int param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 big5hkscs2008_reset(int param_1,gh_u1 *param_2,gh_uint param_3);
extern gh_u4 euc_kr_mbtowc(gh_u4 param_1,gh_u4 param_2,gh_byte *param_3,gh_uint param_4);
extern int euc_kr_wctomb(gh_u4 param_1,char *param_2,gh_u4 param_3,gh_uint param_4);
extern gh_u4 uhc_1_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 uhc_1_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_u4 *param_3,gh_uint param_4);
extern gh_u4 uhc_2_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 uhc_2_wctomb(gh_u4 param_1,gh_u1 *param_2,gh_uint param_3,gh_uint param_4);
extern int cp949_mbtowc(gh_u4 param_1,int *param_2,gh_byte *param_3,gh_uint param_4);
extern int cp949_wctomb(gh_u4 param_1,char *param_2,gh_uint param_3,gh_uint param_4);
extern gh_u4 johab_mbtowc(gh_u4 param_1,gh_uint *param_2,gh_byte *param_3,gh_uint param_4);
extern gh_u4 johab_wctomb(gh_u4 param_1,gh_byte *param_2,gh_uint param_3,gh_uint param_4);
extern gh_uint iso2022_kr_mbtowc(int param_1,gh_u4 param_2,char *param_3,gh_uint param_4);
extern gh_uint iso2022_kr_wctomb(int param_1,char *param_2,int param_3,gh_uint param_4);
extern gh_u4 iso2022_kr_reset(int param_1,gh_u1 *param_2,int param_3);
extern int unicode_transliterate(int param_1,gh_uint param_2,int param_3,gh_uint param_4);
extern void uc_to_mb_write_replacement(void *param_1,gh_uint param_2,int *param_3);
extern void mb_to_uc_write_replacement(gh_uint *param_1,int param_2,int *param_3);
extern int unicode_loop_convert(int param_1,int *param_2,gh_uint *param_3,int *param_4,gh_uint *param_5);
extern int unicode_loop_reset(int param_1,int *param_2,gh_uint *param_3);
extern void wc_to_mb_write_replacement(void *param_1,gh_uint param_2,int *param_3);
extern gh_u4 wchar_from_loop_reset(int param_1,int *param_2,gh_u4 param_3);
extern void mb_to_wc_write_replacement(gh_u4 *param_1,int param_2,int *param_3);
extern int wchar_to_loop_convert(int param_1,int *param_2,gh_uint *param_3,int *param_4,gh_uint *param_5);
extern gh_u4 wchar_to_loop_reset(int param_1,gh_u4 param_2,gh_u4 param_3);
extern gh_u4 wchar_id_loop_convert(int param_1,int *param_2,gh_uint *param_3,int *param_4,gh_uint *param_5);
extern gh_u4 wchar_id_loop_reset(void);
extern int aliases_hash(gh_byte *param_1,int param_2);
extern gh_u1 aliases_lookup(char *param_1,gh_uint param_2,gh_u4 param_3,gh_u4 param_4);
extern gh_u4 libiconv_open(gh_byte *param_1,gh_byte *param_2);
extern gh_u4 libiconv_close(void *param_1);
extern gh_u4 libiconv_open_into(gh_byte *param_1,gh_byte *param_2,gh_u4 *param_3);
extern gh_u4 libiconvctl(int *param_1,gh_u4 param_2,int *param_3);
extern int compare_by_index(int param_1,int param_2);
extern int compare_by_name(gh_u4 *param_1,gh_u4 *param_2);
extern void libiconvlist(gh_code *param_1,gh_u4 param_2);
extern gh_byte iconv_canonicalize(gh_byte *param_1);
extern char locale_charset(void);
extern gh_uint __aeabi_uidiv(gh_uint param_1,gh_uint param_2);
extern void __aeabi_uidivmod(int param_1,int param_2);
extern gh_uint __aeabi_idiv(gh_uint param_1,gh_uint param_2);
extern gh_uint _divsi3_skip_div0_test(gh_uint param_1,gh_uint param_2);
extern void __aeabi_idivmod(int param_1,int param_2);
extern void __aeabi_idiv0(void);
extern void __libc_csu_init(int argc,char **argv,char **envp);
extern void __libc_csu_fini(void);
extern void _fini(void);

#endif