/* proto.h — 函数原型（反编译签名行） */
#ifndef RK_PROTO_H
#define RK_PROTO_H
#include "ghidra_compat.h"
#include "globals.h"

extern void _mxml_fini(void);
extern undefined4 main(void);
extern void _start(undefined4 param_1,undefined4 param_2);
extern void call_weak_fn(void);
extern void deregister_tm_clones(void);
extern void register_tm_clones(void);
extern void __do_global_dtors_aux(void);
extern void frame_dummy(void);
extern void RARCH_LOG_V(char *param_1,__gnuc_va_list param_2);
extern void RARCH_LOG(undefined4 param_1);
extern void GetConfig(void);
extern int get_executable_path(char *param_1,char *param_2,size_t param_3);
extern void dispmeninfo(void);
extern void outputxy1(byte *param_1);
extern void spi_printf(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
extern undefined4 ShareMemCreat(void);
extern undefined4 ShareMemClose(void);
extern void xintiao(void);
extern void XintiaoThread(void);
extern undefined4 UpdateROMProc(int param_1,int param_2);
extern void DateToTmuDate(uint param_1);
extern void UpdateROM(char *param_1);
extern void TestUSBJoy(void);
extern void GetTick(void);
extern void WaitNMI(void);
extern void TestRun(void);
extern undefined4 TestLibz0(void);
extern void TestLibz1(void);
extern void sunxi_gpio_init(void);
extern undefined4 sunxi_gpio_set_cfgpin(int param_1,int param_2);
extern uint sunxi_gpio_get_cfgpin(uint param_1);
extern undefined4 sunxi_gpio_output(int param_1,int param_2);
extern uint sunxi_gpio_input(uint param_1);
extern void sunxi_gpio_cleanup(void);
extern char get_from_line(char *param_1,int param_2);
extern undefined4 GetInputInfo(char *param_1,undefined4 param_2);
extern uint ReadUSBJoy(int param_1);
extern void InitMDJoystick(void);
extern void ReadPS2JS(uint param_1,byte *param_2,byte *param_3);
extern void ReadJoystickProc(void);
extern void processvblank(void);
extern void ReadJoystickThread(void);
extern void timer_thread(void);
extern void SetBacklight(int param_1);
extern void InitIOSignal(void);
extern void OutputIOSignal(void);
extern undefined4 ReadJoystick(void);
extern void osDelay(int param_1);
extern void SPI_WW(uint param_1);
extern uint SPI_RR(void);
extern undefined4 SPI_Read(undefined4 param_1);
extern void SPI_Read_BUF(undefined4 param_1,int param_2,int param_3);
extern void SPI_Write_BUF(undefined4 param_1,int param_2,int param_3);
extern void SPI_Write(undefined4 param_1,undefined4 param_2);
extern void RxMode(void);
extern void TxMode(void);
extern int getticks(void);
extern void RF_Joystick_timer_isr(void);
extern void InitRFJoystick(void);
extern void InitJoystick(void);
extern undefined4 GetDecodeData(void);
extern void InitDecode(void);
extern void ReInitDecode(void);
extern undefined4 ScaleDisplayThread(void);
extern undefined4 run_process_constprop_0(undefined4 param_1);
extern undefined4 InitDisplay(void);
extern void dispFlip(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
extern void video_driver_set_rotation(undefined4 param_1);
extern void video_driver_set_colormode(undefined4 param_1);
extern void DeinitDisplay(void);
extern void InitSound(void);
extern void DeinitSound(void);
extern void PlaySound(void);
extern void zcalloc(void *param_1,uint param_2,uint param_3);
extern void zcfree(void *param_1,void *param_2);
extern int inflate_flush(inflate_blocks_state *param_1,z_stream_s *param_2,int param_3);
extern void inflate_codes_free(inflate_codes_state *param_1,z_stream_s *param_2);
extern void inflate_blocks_reset(inflate_blocks_state *param_1,z_stream_s *param_2,ulong *param_3);
extern undefined4 inflate_blocks_free(inflate_blocks_state *param_1,z_stream_s *param_2);
extern void inflate_codes(inflate_blocks_state *param_1,z_stream_s *param_2,int param_3);
extern void inflate_blocks(inflate_blocks_state *param_1,z_stream_s *param_2,int param_3);
extern undefined1 get_crc_table(void);
extern uint ucrc32(uint param_1,byte *param_2,uint param_3);
extern uint adler32(ulong param_1,uchar *param_2,uint param_3);
extern char zlibVersion(void);
extern undefined zError(int param_1);
extern undefined4 inflateReset(z_stream_s *param_1);
extern undefined4 inflateEnd(z_stream_s *param_1);
extern undefined4 inflateInit2(z_stream_s *param_1);
extern int inflate(z_stream_s *param_1,int param_2);
extern undefined1 lufopen(void *param_1,uint param_2,uint param_3,uint *param_4);
extern undefined4 lufclose(LUFILE *param_1);
extern bool luferror(LUFILE *param_1);
extern int luftell(LUFILE *param_1);
extern int lufseek(LUFILE *param_1,long param_2,int param_3);
extern void lufread(void *param_1,uint param_2,uint param_3,LUFILE *param_4);
extern int unzlocal_getByte(LUFILE *param_1,int *param_2);
extern void unzlocal_getShort(LUFILE *param_1,ulong *param_2);
extern void unzlocal_getLong(LUFILE *param_1,ulong *param_2);
extern int strcmpcasenosensitive_internal(char *param_1,char *param_2);
extern void unzStringFileNameCompare(char *param_1,char *param_2,int param_3);
extern int unzlocal_SearchCentralDir(LUFILE *param_1);
extern undefined4 unzGetGlobalInfo(unz_s *param_1,unz_global_info_s *param_2);
extern void unzlocal_DosDateToTmuDate(ulong param_1,tm_unz_s *param_2);
extern int unzGoToFirstFile(unz_s *param_1);
extern unz_s unzOpenInternal(LUFILE *param_1);
extern int unzGoToNextFile(unz_s *param_1);
extern int unzLocateFile(unz_s *param_1,char *param_2,int param_3);
extern int unzReadCurrentFile(unz_s *param_1,void *param_2,uint param_3);
extern undefined4 unztell(unz_s *param_1);
extern uint unzeof(unz_s *param_1);
extern uint unzGetLocalExtrafield(unz_s *param_1,void *param_2,uint param_3);
extern undefined4 unzCloseCurrentFile(unz_s *param_1);
extern undefined4 unzClose(unz_s *param_1);
extern undefined4 unzOpenCurrentFile(unz_s *param_1);
extern uint unzGetGlobalComment(unz_s *param_1,char *param_2,ulong param_3);
extern void timet2filetime(long param_1);
extern size_t FormatZipMessageU(uint param_1,char *param_2,uint param_3);
extern undefined4 OpenZipU(void *param_1,uint param_2,uint param_3);
extern undefined4 GetZipItemA(int *param_1,int param_2,ZIPENTRY *param_3);
extern int GetZipItemW(HZIP__ *param_1,int param_2,ZIPENTRYW *param_3);
extern undefined4 FindZipItemA(int *param_1,char *param_2,uchar param_3,int *param_4,ZIPENTRY *param_5);
extern int FindZipItemW(HZIP__ *param_1,char *param_2,uchar param_3,int *param_4,ZIPENTRYW *param_5);
extern undefined4 UnzipItem(int *param_1,int param_2,void *param_3,uint param_4,uint param_5);
extern undefined4 CloseZipU(int *param_1);
extern bool IsZipHandleU(HZIP__ *param_1);
extern void stbtt__cff_get_index(int *param_1,int *param_2);
extern uint stbtt__cff_int(int *param_1);
extern void stbtt__dict_get_ints(int *param_1,uint param_2,int param_3,int param_4);
extern bool stbtt__isfont(char *param_1);
extern int stbtt__find_table(int param_1,int param_2,char *param_3);
extern undefined4 stbtt__get_subrs(undefined4 *param_1,int param_2,undefined4 param_3,int param_4);
extern int stbtt__GetGlyfOffset(int param_1,int param_2);
extern void stbtt__track_vertex(int param_1,int param_2,int param_3);
extern void stbtt__csctx_close_shape(int param_1);
extern void stbtt__csctx_rmove_to(int param_1);
extern void stbtt__csctx_rline_to(float param_1,float param_2,int param_3);
extern void stbtt__sort_edges_quicksort(undefined4 *param_1,int param_2);
extern int stbtt__CompareUTF8toUTF16_bigendian_prefix(int param_1,int param_2,byte *param_3,int param_4);
extern bool stbtt__matchpair(int param_1,int param_2,int param_3,int param_4,int param_5,int param_6);
extern void DrawSelectBar(int *param_1);
extern void mui_blockcopy(int *param_1,int *param_2);
extern void UnDrawSelectBar(int *param_1,int param_2,int param_3);
extern void mui_DispBlock(int param_1,int param_2,int param_3,int param_4);
extern void mui_UnDispBlock(int param_1,int param_2,int *param_3,int param_4);
extern void mui_Undisplay(int param_1,int param_2,int param_3,int param_4);
extern void stbtt__h_prefilter(int param_1,uint param_2,int param_3,int param_4,size_t param_5);
extern void stbtt__v_prefilter(int param_1,int param_2,uint param_3,int param_4,size_t param_5);
extern void mui_extract_basepath(char *param_1,char *param_2,int param_3);
extern void mui_extract_basename(char *param_1,char *param_2,int param_3);
extern void mui_DisplayThumbnail(void);
extern long buttontoi(char *param_1);
extern void stbtt__cff_index_get_isra_2(undefined4 *param_1,undefined1 *param_2,uint param_3,int param_4);
extern undefined4 stbtt__run_charstring(int param_1,int param_2,undefined4 param_3);
extern int stbtt__GetGlyphClass(byte *param_1,int param_2);
extern float stbtt__cuberoot(float param_1);
extern int code_convert_constprop_22(undefined4 param_1,undefined4 param_2,void *param_3,size_t param_4);
extern byte strupr(byte *param_1);
extern undefined4 FilePreEmu(char *param_1);
extern undefined1 GetWorkPath(void);
extern void mui_LoadSetting(void);
extern undefined4 mui_LoadUIResource(undefined4 *param_1,undefined4 param_2);
extern void shoucang(char *param_1);
extern undefined4 IsShoucang(char *param_1);
extern int mui_do_file_list(int param_1,byte *param_2);
extern int mui_type_file_list(int param_1,byte *param_2);
extern int mui_search_file_list(int param_1,int param_2);
extern int GetTicks(void);
extern void mui_DisplayThumbnailThread(void);
extern void mui_WaitNMI(void);
extern uint stbtt_FindGlyphIndex(int param_1,uint param_2);
extern bool stbtt_IsGlyphEmpty(int param_1,undefined4 param_2);
extern void stbtt_GetGlyphShape(int param_1,undefined4 param_2,undefined4 *param_3);
extern void stbtt_GetCodepointShape(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern void stbtt_GetGlyphHMetrics(int param_1,int param_2,int *param_3,int *param_4);
extern int stbtt_GetGlyphKernAdvance(int param_1,int param_2,uint param_3);
extern undefined4 stbtt_GetCodepointKernAdvance(int param_1,undefined4 param_2,undefined4 param_3);
extern void stbtt_GetFontVMetrics(int param_1,int *param_2,int *param_3,int *param_4);
extern undefined4 stbtt_GetFontVMetricsOS2(int param_1,int *param_2,int *param_3,int *param_4);
extern void stbtt_GetFontBoundingBox(int param_1,int *param_2,int *param_3,int *param_4,int *param_5);
extern float stbtt_ScaleForPixelHeight(float param_1,int param_2);
extern float stbtt_ScaleForMappingEmToPixels(float param_1,int param_2);
extern void stbtt_FreeShape(undefined4 param_1,void *param_2);
extern void stbtt_GetGlyphBitmapBox(undefined4 param_1,undefined4 param_2);
extern int mui_outputxy_length_isra_19(int param_1,int param_2,byte *param_3);
extern void stbtt_GetCodepointBitmapBox(undefined4 param_1,undefined4 param_2);
extern void stbtt_FreeBitmap(void *param_1);
extern void stbtt_GetGlyphBitmap(undefined4 param_1,undefined4 param_2);
extern void stbtt_MakeGlyphBitmap(undefined4 param_1,undefined4 param_2);
extern int mui_outputxy_t(int param_1,int param_2,int param_3,int param_4,uint param_5,byte *param_6);
extern void mui_DisplayGameSum(void);
extern void mui_DisplayLine_t(int param_1,int param_2,int param_3);
extern void mui_DisplayInputBuffer(void);
extern void stbtt_GetCodepointBitmap(undefined4 param_1,undefined4 param_2);
extern void stbtt_MakeCodepointBitmap(undefined4 param_1,undefined4 param_2);
extern void stbtt_PackEnd(int param_1);
extern void stbtt_PackSetOversampling(int param_1,uint param_2,uint param_3);
extern void stbtt_PackSetSkipMissingCodepoints(int param_1,undefined4 param_2);
extern void stbtt_PackFontRangesPackRects(int param_1,int *param_2,int param_3);
extern void stbtt_FreeSDF(void *param_1);
extern int stbtt_GetFontOffsetForIndex(char *param_1);
extern int stbtt_GetNumberOfFonts(undefined4 param_1);
extern undefined4 stbtt_InitFont(int param_1,int param_2,undefined4 param_3);
extern void stbtt_PackFontRange(void);
extern void mui_InitFont(void);
extern int stbtt_FindMatchingFont(int param_1,char *param_2,uint param_3);
extern bool stbtt_CompareUTF8toUTF16_bigendian(void);
extern char strtrimr(char *param_1);
extern byte strtriml(byte *param_1);
extern void strtrim(void);
extern char get_item_from_line(undefined4 param_1,char *param_2);
extern int get_items_from_file(char *param_1,int param_2);
extern int get_items_from_zipfile(undefined4 param_1,int param_2);
extern char get_value_from_items(char *param_1,char *param_2,char *param_3,int param_4);
extern void mui_LoadConfig(void);
extern void gameType(void);
extern void LoadMenuLog(void);
extern void SaveMenuLog(void);
extern uint mui_ReadJoystick(void);
extern int dir_serial_list(int param_1);
extern void outputblankxy(int param_1,int param_2,int param_3,int param_4);
extern void DisplayLine_list(undefined4 param_1,int param_2,int param_3);
extern void DisplayPage_list(int param_1,undefined4 param_2,int param_3);
extern char myStrrstr(char *param_1,char *param_2);
extern void EmuCore_Blank(int param_1,int param_2,int param_3,int param_4);
extern void EmuCore_Line(int param_1,int param_2,int param_3);
extern void EmuCore_list(int param_1,undefined4 param_2,int param_3);
extern int SeletEmuCore(undefined4 param_1);
extern undefined4 GetFileCore(char *param_1);
extern undefined4 ui_GetVolume(void);
extern void SoundClose(int param_1);
extern void ui_deinit(void);
extern void SoundPlay(int param_1,int *param_2);
extern undefined4 filelist_run_game(char *param_1);
extern undefined4 mui_run_game(char *param_1);
extern void mui_menu(void);
extern void mui_type(void);
extern void mui_search(void);
extern undefined4 Mp3DecodeLoop(int param_1);
extern void AudioProcess(void);
extern void mui_SoundplayThread(void);
extern void LoadDefaultState(void);
extern void SaveDefaultState(void);
extern void InitKeyMapping0fEmuType(void);
extern void SaveKeyMappingConfigFile(void);
extern void blockadaptive(int *param_1,int *param_2);
extern void popwindows(undefined4 *param_1);
extern void popoffwindows(undefined4 *param_1);
extern void mui_recent(void);
extern void mui_shoucang(void);
extern void blockcopy(int *param_1,int *param_2);
extern void draw_state_select(int param_1,int param_2,int param_3);
extern void progress(char *param_1,undefined4 param_2);
extern void spi_memcpy(void);
extern void InitScr(void);
extern undefined4 GetJoystickConfig(int param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
extern void JoystickTest(int param_1);
extern void mui_setting(void);
extern void main_Menu(void);
extern undefined4 mui_joystick_setting(void);
extern undefined4 mui_video_setting(void);
extern undefined4 mui_load_state(void);
extern undefined4 mui_save_state(void);
extern undefined4 mui_game_exit(void);
extern undefined4 PauseMenu(void);
extern void FUN_00095132(void);
extern void __ErrorSoundEnd(void);
extern undefined4 __SetTruboSoundEnd(undefined4 param_1);
extern void joystick_poll(void);
extern undefined4 PlayFrame(undefined4 param_1,undefined4 param_2);
extern undefined4 gpsp_unzip(undefined4 param_1,undefined4 param_2);
extern void log_dummy(uint param_1,undefined4 param_2);
extern bool joystick_input(uint param_1,undefined4 param_2,undefined4 param_3,int param_4);
extern undefined4 environment(int param_1,uint *param_2);
extern void UIDebug(int param_1,int param_2,undefined4 param_3,uint param_4);
extern void DrawFrame(undefined2 *param_1,int param_2,int param_3,int param_4);
extern void rgb8888_to_rgb565(ushort *param_1,int param_2,int param_3);
extern int GetCoreIndex(char *param_1);
extern char GetFilenameExt(char *param_1);
extern void extract_basepath(char *param_1,char *param_2,int param_3);
extern void init_user_joy_key_mask(int param_1,undefined4 param_2);
extern void TurboKeyProcess(void);
extern undefined4 run_process(undefined4 param_1,int param_2);
extern void RetroInitSound(void);
extern bool Load_Proc1(char *param_1);
extern void Load_Proc2(void);
extern undefined4 Snes_Load(char *param_1,int param_2);
extern undefined4 TGB_Load(char *param_1,int param_2);
extern undefined4 prosystem_Load(char *param_1,int param_2);
extern undefined4 stella_Load(char *param_1,int param_2);
extern undefined4 PCSX_Load(char *param_1);
extern undefined4 FBA_Load(char *param_1);
extern undefined4 Core_Load(char *param_1,undefined4 param_2);
extern undefined4 Gpsp_Load(char *param_1,int param_2);
extern undefined4 run_game(char *param_1);
extern void autorun(undefined4 param_1,char *param_2);
extern undefined4 NES_Load(char *param_1,int param_2);
extern undefined4 GBC_Load(char *param_1,int param_2);
extern undefined4 VRT_Load(char *param_1,int param_2);
extern undefined4 Pico_Load(char *param_1,int param_2);
extern undefined4 retro_save_state(char *param_1);
extern undefined4 retro_load_state(char *param_1);
extern void MP3FreeDecoder(int param_1);
extern int MP3FindSyncWord(byte *param_1,int param_2);
extern void MP3GetLastFrameInfo(int param_1,undefined4 *param_2);
extern undefined4 MP3GetNextFrameInfo(int param_1,undefined4 param_2,undefined4 param_3);
extern undefined4 MP3Decode(int param_1,int *param_2,int *param_3,int param_4,int param_5);
extern void Convert_Stereo(undefined2 *param_1);
extern void Convert_Mono(undefined2 *param_1);
extern void xmp3_MidSideProc(int param_1,int param_2,uint *param_3);
extern undefined4 xmp3_Subband(int param_1,int param_2);
extern void WinPrevious(int *param_1,int *param_2,int param_3);
extern uint FreqInvertRescale(int param_1,int param_2,uint param_3,uint param_4);
extern undefined4 xmp3_IMDCT(undefined4 *param_1,int param_2,int param_3);
extern uint DequantBlock(uint *param_1,int param_2,int param_3,uint param_4);
extern undefined4 xmp3_Dequantize(undefined4 *param_1,int param_2);
extern void xmp3_FDCT32(uint *param_1,int param_2,int param_3,int param_4,int param_5);
extern void xmp3_SetBitstreamPointer(undefined4 *param_1,undefined4 param_2,undefined4 param_3);
extern uint xmp3_GetBits(undefined4 *param_1,uint param_2);
extern int xmp3_CalcBitsUsed(int *param_1,int param_2,int param_3);
extern uint xmp3_CheckPadBit(int *param_1);
extern undefined4 xmp3_UnpackFrameHeader(int *param_1,char *param_2);
extern undefined4 xmp3_UnpackSideInfo(undefined4 *param_1,undefined4 param_2);
extern void ClearBuffer(undefined1 *param_1,int param_2);
extern undefined1 xmp3_AllocateBuffers(void);
extern void xmp3_FreeBuffers(void);
extern void xmp3_PolyphaseMono(ushort *param_1,int *param_2,int *param_3);
extern void xmp3_PolyphaseStereo(ushort *param_1,int *param_2,int *param_3);
extern undefined4 mxml_set_attr(int param_1,char *param_2,undefined4 param_3);
extern void mxmlElementDeleteAttr(int *param_1,char *param_2);
extern undefined4 mxmlElementGetAttr(int *param_1,char *param_2);
extern void mxmlElementSetAttr(int *param_1,int param_2,int param_3);
extern void mxmlElementSetAttrf(int *param_1,int param_2,int param_3);
extern undefined4 mxmlEntityAddCallback(undefined4 param_1);
extern undefined mxmlEntityGetName(undefined4 param_1);
extern int mxmlEntityGetValue(undefined4 param_1);
extern void mxmlEntityRemoveCallback(int param_1);
extern undefined4 _mxml_entity_cb(char *param_1);
extern undefined4 mxml_string_putc(undefined1 param_1,undefined4 *param_2);
extern uint mxml_string_getc(undefined4 *param_1,int *param_2);
extern uint mxml_get_entity(int param_1,undefined4 param_2,undefined4 param_3,code *param_4);
extern undefined4 mxml_add_char(uint param_1,int *param_2,int *param_3,size_t *param_4);
extern uint mxml_file_getc(_IO_FILE *param_1,int *param_2);
extern undefined4 mxml_write_string(char *param_1,undefined4 param_2,code *param_3);
extern undefined4 mxml_fd_write(int *param_1);
extern undefined4 mxml_fd_putc(undefined1 param_1,int param_2);
extern int mxml_file_putc(int param_1,_IO_FILE *param_2);
extern bool mxml_isspace_part_0(int param_1);
extern undefined4 mxml_fd_read_part_1(int *param_1);
extern uint mxml_fd_getc(int param_1,int *param_2);
extern int mxml_write_name(char *param_1,undefined4 param_2,code *param_3);
extern void mxmlLoadFd(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern void mxmlLoadFile(void);
extern void mxmlLoadString(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern undefined4 mxmlSaveFd(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern int mxmlSaveFile(undefined4 param_1,_IO_FILE *param_2,undefined4 param_3);
extern int mxmlSaveString(undefined4 param_1,undefined1 *param_2,int param_3,undefined4 param_4);
extern void mxmlSaveAllocString(undefined4 param_1,undefined4 param_2);
extern void mxmlSAXLoadFile(void);
extern void mxmlSetCustomHandlers(undefined4 param_1,undefined4 param_2);
extern void mxmlSetErrorCallback(undefined4 param_1);
extern void mxmlSetWrapMargin(undefined4 param_1);
extern char mxmlGetCDATA(int *param_1);
extern int mxmlGetCustom(int *param_1);
extern int mxmlGetElement(int *param_1);
extern int mxmlGetFirstChild(int *param_1);
extern int mxmlGetInteger(int *param_1);
extern int mxmlGetLastChild(int *param_1);
extern undefined4 mxmlGetNextSibling(int param_1);
extern int mxmlGetOpaque(int *param_1);
extern undefined4 mxmlGetParent(int param_1);
extern undefined4 mxmlGetPrevSibling(int param_1);
extern undefined4 mxmlGetReal(int *param_1);
extern int mxmlGetText(int *param_1,int *param_2);
extern undefined4 mxmlGetType(undefined4 *param_1);
extern undefined4 mxmlGetUserData(int param_1);
extern int index_find_isra_0(undefined4 *param_1,char *param_2,char *param_3,int param_4);
extern void index_compare_isra_2(int *param_1,int param_2,int param_3);
extern void index_sort(int param_1,int param_2,int param_3);
extern void mxmlIndexDelete(undefined4 *param_1);
extern undefined4 mxmlIndexEnum(int param_1);
extern undefined4 mxmlIndexFind(int *param_1,int param_2,int param_3);
extern undefined4 mxmlIndexGetCount(int param_1);
extern undefined4 mxmlIndexNew(int param_1,int param_2,int param_3);
extern undefined4 mxmlIndexReset(int param_1);
extern undefined4 mxmlGetRefCount(int param_1);
extern void mxmlRemove(int param_1);
extern void mxmlAdd(int param_1,int param_2,int param_3,int param_4);
extern undefined4 mxml_new(int param_1,undefined4 param_2);
extern int mxmlNewCDATA(undefined4 param_1,int param_2);
extern void mxmlNewCustom(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern int mxmlNewElement(undefined4 param_1,int param_2);
extern void mxmlNewInteger(undefined4 param_1,undefined4 param_2);
extern int mxmlNewOpaque(undefined4 param_1,int param_2);
extern void mxmlNewReal(undefined4 param_1);
extern int mxmlNewText(undefined4 param_1,undefined4 param_2,int param_3);
extern int mxmlNewTextf(undefined4 param_1,undefined4 param_2,int param_3);
extern void mxmlDelete(undefined4 *param_1);
extern void mxmlNewXML(undefined *param_1);
extern int mxmlRelease(int param_1);
extern void mxmlRetain(int param_1);
extern void _mxml_destructor(void *param_1);
extern void _mxml_init(void);
extern undefined4 mxml_ignore_cb(void);
extern undefined4 mxml_integer_cb(void);
extern undefined4 mxml_opaque_cb(void);
extern undefined4 mxml_real_cb(void);
extern void _mxml_global(void);
extern void mxml_error(char *param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
extern int mxmlWalkNext(int param_1,int param_2,int param_3);
extern int mxmlFindElement(int param_1,int param_2,char *param_3,int param_4,char *param_5,int param_6);
extern int mxmlFindPath(int *param_1,char *param_2);
extern int mxmlWalkPrev(int param_1,int param_2,int param_3);
extern undefined4 mxmlSetCDATA(int *param_1,int param_2);
extern undefined4 mxmlSetCustom(int *param_1,int param_2,int param_3);
extern undefined4 mxmlSetElement(int *param_1,int param_2);
extern undefined4 mxmlSetInteger(int *param_1,int param_2);
extern undefined4 mxmlSetOpaque(int *param_1,int param_2);
extern undefined4 mxmlSetReal(int *param_1);
extern undefined4 mxmlSetText(int *param_1,int param_2,int param_3);
extern undefined4 mxmlSetTextf(int *param_1,int param_2,int param_3);
extern undefined4 mxmlSetUserData(int param_1,undefined4 param_2);
extern char _mxml_vstrdupf(char *param_1,__gnuc_va_list param_2);
extern void _mxml_strdupf(undefined4 param_1);
extern uint sfc_request(uint *param_1,uint param_2,uint *param_3,uint param_4);
extern int snor_wait_busy(int param_1);
extern void snor_write_en(void);
extern void spi_write(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern void erase_sector(undefined4 param_1);
extern void spi_read(undefined4 param_1,undefined4 param_2,undefined4 param_3);
extern void sflash_write_security_data(undefined4 param_1,undefined4 param_2);
extern void sflash_erase_security_data(undefined4 param_1);
extern void sflash_read_security_data(undefined4 param_1,undefined4 param_2);
extern undefined4 spi_driver_init(void);
extern undefined4 sfc_uninit(void);
extern undefined4 sfc_init(void);
extern undefined4 ascii_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 ascii_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3);
extern undefined4 utf8_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern uint utf8_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern uint ucs2_mbtowc(int param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 ucs2_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 ucs2be_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 ucs2be_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 ucs2le_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 ucs2le_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern uint ucs4_mbtowc(int param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 ucs4_wctomb(undefined4 param_1,undefined1 *param_2,int param_3,uint param_4);
extern undefined4 ucs4be_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 ucs4be_wctomb(undefined4 param_1,undefined1 *param_2,undefined4 param_3,uint param_4);
extern undefined4 ucs4le_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 ucs4le_wctomb(undefined4 param_1,undefined1 *param_2,undefined4 param_3,uint param_4);
extern uint utf16_mbtowc(int param_1,int *param_2,byte *param_3,uint param_4);
extern int utf16_wctomb(int param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern undefined4 utf16be_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 utf16be_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern undefined4 utf16le_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 utf16le_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern uint utf32_mbtowc(int param_1,undefined4 *param_2,byte *param_3,uint param_4);
extern int utf32_wctomb(int param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern undefined4 utf32be_mbtowc(undefined4 param_1,undefined4 *param_2,byte *param_3,uint param_4);
extern undefined4 utf32be_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern undefined4 utf32le_mbtowc(undefined4 param_1,undefined4 *param_2,byte *param_3,uint param_4);
extern undefined4 utf32le_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern uint utf7_mbtowc(int param_1,uint *param_2,byte *param_3,uint param_4);
extern uint utf7_wctomb(int param_1,char *param_2,undefined *param_3,uint param_4);
extern uint utf7_reset(int param_1,char *param_2,uint param_3);
extern undefined4 ucs2internal_mbtowc(undefined4 param_1,uint *param_2,ushort *param_3,uint param_4);
extern undefined4 ucs2internal_wctomb(undefined4 param_1,undefined2 *param_2,uint param_3,uint param_4);
extern undefined4 ucs2swapped_mbtowc(undefined4 param_1,uint *param_2,ushort *param_3,uint param_4);
extern undefined4 ucs2swapped_wctomb(undefined4 param_1,ushort *param_2,uint param_3,uint param_4);
extern undefined4 ucs4swapped_mbtowc(undefined4 param_1,uint *param_2,uint *param_3,uint param_4);
extern undefined4 ucs4swapped_wctomb(undefined4 param_1,uint *param_2,uint param_3,uint param_4);
extern undefined4 c99_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern uint c99_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 java_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 java_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern undefined4 iso8859_1_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_1_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3);
extern undefined4 iso8859_2_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_2_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_3_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_3_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_4_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_4_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_5_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_5_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_6_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_6_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_7_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_7_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_8_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_8_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_9_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_9_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_10_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_10_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_11_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_11_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_13_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_13_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_14_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_14_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_15_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_15_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 iso8859_16_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso8859_16_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 koi8_r_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 koi8_r_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 koi8_u_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 koi8_u_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 koi8_ru_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 koi8_ru_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1250_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1250_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1251_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1251_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1252_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1252_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1253_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1253_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1254_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1254_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern bool normal_flushwc(int param_1,int *param_2);
extern undefined4 cp1255_mbtowc(int param_1,uint *param_2,byte *param_3);
extern undefined4 cp1255_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 cp1256_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1256_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1257_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1257_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1258_mbtowc(int param_1,uint *param_2,byte *param_3);
extern undefined4 cp1258_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 cp850_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp850_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp862_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp862_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp866_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp866_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1131_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1131_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_roman_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_roman_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_centraleurope_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_centraleurope_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_iceland_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_iceland_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_croatian_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_croatian_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_romania_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_romania_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_cyrillic_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_cyrillic_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_ukraine_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_ukraine_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_greek_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_greek_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_turkish_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_turkish_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_hebrew_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_hebrew_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_arabic_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_arabic_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mac_thai_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mac_thai_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 hp_roman8_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 hp_roman8_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 nextstep_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 nextstep_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 armscii_8_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 armscii_8_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 georgian_academy_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 georgian_academy_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 georgian_ps_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 georgian_ps_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 koi8_t_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 koi8_t_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 pt154_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 pt154_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 rk1048_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 rk1048_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 mulelao_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 mulelao_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp1133_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp1133_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 tis620_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 tis620_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp874_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp874_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 viscii_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 viscii_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 tcvn_mbtowc(int param_1,uint *param_2,byte *param_3);
extern undefined4 tcvn_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 iso646_jp_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso646_jp_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3);
extern undefined4 jisx0201_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 jisx0201_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 jisx0208_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 jisx0208_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 jisx0212_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 jisx0212_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 iso646_cn_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 iso646_cn_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3);
extern undefined4 gb2312_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 gb2312_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 isoir165ext_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 isoir165ext_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern int isoir165_mbtowc(undefined4 param_1,undefined4 param_2,char *param_3,uint param_4);
extern undefined4 isoir165_wctomb(undefined4 param_1,byte *param_2,undefined4 param_3,uint param_4);
extern undefined4 gbkext1_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 gbkext2_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 gbkext_inv_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 cp936ext_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cp936ext_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern int gbk_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 gbk_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 cns11643_1_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_2_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_3_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_4_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_5_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_6_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_7_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_15_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cns11643_inv_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 big5_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 big5_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 ksc5601_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 ksc5601_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 johab_hangul_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 johab_hangul_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern int johab_hangul_decompose(undefined4 param_1,int *param_2,undefined4 param_3);
extern undefined4 euc_jp_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern int euc_jp_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 sjis_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 sjis_wctomb(undefined4 param_1,byte *param_2,uint param_3,uint param_4);
extern undefined4 cp932ext_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 cp932ext_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 cp932_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 cp932_wctomb(undefined4 param_1,byte *param_2,uint param_3,uint param_4);
extern uint iso2022_jp_mbtowc(int param_1,undefined4 param_2,char *param_3,uint param_4);
extern uint iso2022_jp_wctomb(int param_1,char *param_2,undefined4 param_3,uint param_4);
extern undefined4 iso2022_jp_reset(int param_1,undefined1 *param_2,uint param_3);
extern uint iso2022_jp1_mbtowc(int param_1,undefined4 param_2,char *param_3,uint param_4);
extern uint iso2022_jp1_wctomb(int param_1,char *param_2,undefined4 param_3,uint param_4);
extern undefined4 iso2022_jp1_reset(int param_1,undefined1 *param_2,uint param_3);
extern uint iso2022_jp2_mbtowc(int param_1,int *param_2,char *param_3,uint param_4);
extern uint iso2022_jp2_wctomb(int param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 iso2022_jp2_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 cp50221_0208_ext_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp50221_0208_ext_wctomb(undefined4 param_1,char *param_2,uint param_3);
extern undefined4 cp50221_0212_ext_mbtowc(undefined4 param_1,uint *param_2,byte *param_3);
extern undefined4 cp50221_0212_ext_wctomb(undefined4 param_1,char *param_2,char *param_3);
extern uint iso2022_jpms_mbtowc(int param_1,uint *param_2,byte *param_3,uint param_4);
extern uint iso2022_jpms_wctomb(int param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 iso2022_jpms_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 euc_cn_mbtowc(undefined4 param_1,undefined4 param_2,byte *param_3,uint param_4);
extern int euc_cn_wctomb(undefined4 param_1,char *param_2,undefined4 param_3,uint param_4);
extern undefined4 ces_gbk_mbtowc(undefined4 param_1,undefined4 param_2,byte *param_3,uint param_4);
extern int ces_gbk_wctomb(undefined4 param_1,undefined1 *param_2,undefined4 param_3,uint param_4);
extern int cp936_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern int cp936_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 gb18030ext_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 gb18030ext_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern undefined4 gb18030uni_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 gb18030uni_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern int gb18030_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern int gb18030_wctomb(undefined4 param_1,char *param_2,undefined *param_3,uint param_4);
extern uint iso2022_cn_mbtowc(int param_1,int *param_2,char *param_3,uint param_4);
extern uint iso2022_cn_wctomb(int param_1,char *param_2,int param_3,uint param_4);
extern undefined4 iso2022_cn_reset(int param_1,undefined1 *param_2,int param_3);
extern uint iso2022_cn_ext_mbtowc(int param_1,int *param_2,char *param_3,uint param_4);
extern uint iso2022_cn_ext_wctomb(int param_1,char *param_2,int param_3,uint param_4);
extern undefined4 iso2022_cn_ext_reset(int param_1,undefined1 *param_2,int param_3);
extern uint hz_mbtowc(int param_1,uint *param_2,byte *param_3,uint param_4);
extern uint hz_wctomb(int param_1,char *param_2,undefined4 param_3,uint param_4);
extern undefined4 hz_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 euc_tw_mbtowc(undefined4 param_1,undefined4 param_2,byte *param_3,uint param_4);
extern int euc_tw_wctomb(undefined4 param_1,char *param_2,undefined4 param_3,uint param_4);
extern undefined4 ces_big5_mbtowc(undefined4 param_1,undefined4 param_2,byte *param_3,uint param_4);
extern int ces_big5_wctomb(undefined4 param_1,undefined1 *param_2,undefined4 param_3,uint param_4);
extern undefined4 cp950ext_mbtowc(undefined4 param_1,uint *param_2,char *param_3,uint param_4);
extern undefined4 cp950ext_wctomb(undefined4 param_1,undefined1 *param_2,undefined *param_3,uint param_4);
extern int cp950_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern int cp950_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 hkscs1999_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 hkscs1999_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern int big5hkscs1999_mbtowc(int param_1,int *param_2,byte *param_3,uint param_4);
extern uint big5hkscs1999_wctomb(int param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 big5hkscs1999_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 hkscs2001_mbtowc(undefined4 param_1,uint *param_2,char *param_3,uint param_4);
extern undefined4 hkscs2001_wctomb(undefined4 param_1,undefined1 *param_2,word *param_3,uint param_4);
extern int big5hkscs2001_mbtowc(int param_1,int *param_2,byte *param_3,uint param_4);
extern uint big5hkscs2001_wctomb(int param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 big5hkscs2001_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 hkscs2004_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 hkscs2004_wctomb(undefined4 param_1,undefined1 *param_2,code *param_3,uint param_4);
extern int big5hkscs2004_mbtowc(int param_1,int *param_2,byte *param_3,uint param_4);
extern uint big5hkscs2004_wctomb(int param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 big5hkscs2004_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 hkscs2008_mbtowc(undefined4 param_1,uint *param_2,char *param_3,uint param_4);
extern undefined4 hkscs2008_wctomb(undefined4 param_1,undefined1 *param_2,code *param_3,uint param_4);
extern int big5hkscs2008_mbtowc(int param_1,int *param_2,byte *param_3,uint param_4);
extern uint big5hkscs2008_wctomb(int param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 big5hkscs2008_reset(int param_1,undefined1 *param_2,uint param_3);
extern undefined4 euc_kr_mbtowc(undefined4 param_1,undefined4 param_2,byte *param_3,uint param_4);
extern int euc_kr_wctomb(undefined4 param_1,char *param_2,undefined4 param_3,uint param_4);
extern undefined4 uhc_1_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 uhc_1_wctomb(undefined4 param_1,undefined1 *param_2,undefined4 *param_3,uint param_4);
extern undefined4 uhc_2_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern undefined4 uhc_2_wctomb(undefined4 param_1,undefined1 *param_2,uint param_3,uint param_4);
extern int cp949_mbtowc(undefined4 param_1,int *param_2,byte *param_3,uint param_4);
extern int cp949_wctomb(undefined4 param_1,char *param_2,uint param_3,uint param_4);
extern undefined4 johab_mbtowc(undefined4 param_1,uint *param_2,byte *param_3,uint param_4);
extern undefined4 johab_wctomb(undefined4 param_1,byte *param_2,uint param_3,uint param_4);
extern uint iso2022_kr_mbtowc(int param_1,undefined4 param_2,char *param_3,uint param_4);
extern uint iso2022_kr_wctomb(int param_1,char *param_2,int param_3,uint param_4);
extern undefined4 iso2022_kr_reset(int param_1,undefined1 *param_2,int param_3);
extern int unicode_transliterate(int param_1,uint param_2,int param_3,uint param_4);
extern void uc_to_mb_write_replacement(void *param_1,uint param_2,int *param_3);
extern void mb_to_uc_write_replacement(uint *param_1,int param_2,int *param_3);
extern int unicode_loop_convert(int param_1,int *param_2,uint *param_3,int *param_4,uint *param_5);
extern int unicode_loop_reset(int param_1,int *param_2,uint *param_3);
extern void wc_to_mb_write_replacement(void *param_1,uint param_2,int *param_3);
extern undefined4 wchar_from_loop_reset(int param_1,int *param_2,undefined4 param_3);
extern void mb_to_wc_write_replacement(undefined4 *param_1,int param_2,int *param_3);
extern int wchar_to_loop_convert(int param_1,int *param_2,uint *param_3,int *param_4,uint *param_5);
extern undefined4 wchar_to_loop_reset(int param_1,undefined4 param_2,undefined4 param_3);
extern undefined4 wchar_id_loop_convert(int param_1,int *param_2,uint *param_3,int *param_4,uint *param_5);
extern undefined4 wchar_id_loop_reset(void);
extern int aliases_hash(byte *param_1,int param_2);
extern undefined1 aliases_lookup(char *param_1,uint param_2,undefined4 param_3,undefined4 param_4);
extern undefined4 libiconv_open(byte *param_1,byte *param_2);
extern undefined4 libiconv_close(void *param_1);
extern undefined4 libiconv_open_into(byte *param_1,byte *param_2,undefined4 *param_3);
extern undefined4 libiconvctl(int *param_1,undefined4 param_2,int *param_3);
extern int compare_by_index(int param_1,int param_2);
extern int compare_by_name(undefined4 *param_1,undefined4 *param_2);
extern void libiconvlist(code *param_1,undefined4 param_2);
extern byte iconv_canonicalize(byte *param_1);
extern char locale_charset(void);
extern uint __aeabi_uidiv(uint param_1,uint param_2);
extern void __aeabi_uidivmod(int param_1,int param_2);
extern uint __aeabi_idiv(uint param_1,uint param_2);
extern uint _divsi3_skip_div0_test(uint param_1,uint param_2);
extern void __aeabi_idivmod(int param_1,int param_2);
extern void __aeabi_idiv0(void);
extern void __libc_csu_init(int argc,char **argv,char **envp);
extern void __libc_csu_fini(void);
extern void _fini(void);

#endif