import re

# 13 个数组全局：(名称, 尺寸 N)。全部保持 extern unsigned char NAME[N] 不变，
# 另生成 NAME_t 覆盖结构 + NAME_blob 指针 cast 宏，成员访问改走宏。
# 尺寸取自 collect_array_spec.py（globals.h 声明，非猜测）。
SPECS = [
    ("P1_Table", 220), ("fontname", 32), ("m_joysticktab", 924), ("m_menulog", 444),
    ("m_statetab", 144), ("InputDeviceInfo", 112), ("SoundPlayer", 72), ("fpsbuf", 64),
    ("game_joy_key", 16), ("mui_Effect0", 36), ("mui_Effect1", 36),
    ("mui_MenuMusic", 36), ("spi_id", 3), ("ze", 304),
]

def emit(name, N):
    L = []
    L.append(f'typedef union {{')
    L.append(f'    unsigned char raw[{N}];')
    L.append(f'    struct {{')
    w = 0
    full = (N // 4) * 4
    while w < full:
        L.append(f'        union {{ struct {{ unsigned char _{w}_1_, _{w+1}_1_, _{w+2}_1_, _{w+3}_1_; }}; unsigned int _{w}_4_; }};')
        w += 4
    if N % 4:
        # 尾部 N%4 个字节（如 spi_id N=3）：普通字符串拼接，花括号直接写字面，避免 f-string 双花括号转义
        L.append('        struct { unsigned char ' + ', '.join(f'_{b}_1_' for b in range(full, N)) + '; };')
    L.append(f'    }};')
    L.append(f'}} {name}_t;')
    L.append(f'#define {name}_blob (*({name}_t*)&{name})')
    return '\n'.join(L)

body = '\n\n'.join(emit(n, s) for n, s in SPECS)
hdr = ('/* named_array_blobs.h — GENERATED by tools/gen_named_array_blobs.py\n'
       ' * 13 个以 _N_M_ 成员访问的数组全局的精确尺寸覆盖结构 + 指针 cast 宏。\n'
       ' * 尺寸证据：collect_array_spec.py（globals.h 声明 + 函数文件实际访问）。\n'
       ' * 原 extern unsigned char NAME[N] 保持不变 → 零 ABI 变化；成员访问经 NAME_blob 宏。\n'
       ' * 每个 4 对齐窗口同时提供 _w_1_ 字节与 _w_4_ 字（覆盖 M∈{1,4}，4 字节全 4 对齐）。*/\n'
       '#ifndef RK_NAMED_ARRAY_BLOBS_H\n#define RK_NAMED_ARRAY_BLOBS_H\n\n'
       + body + '\n\n#endif\n')
open('src/compat/named_array_blobs.h', 'w', encoding='utf-8').write(hdr)
print('written named_array_blobs.h for', len(SPECS), 'globals,', len(hdr), 'chars')
