import re, glob

ROOT='.'
# Array globals: (name, size, need_dyn_index_byte_array)
ARRAYS = [
    ("P1_Table",220,False),
    ("fontname",32,True),       # mui_InitFont has fontname[8]=0
    ("m_joysticktab",924,False),
    ("m_menulog",444,True),     # mui_setting m_menulog[sVar4+0x1bb]
    ("m_statetab",144,False),
    ("InputDeviceInfo",112,False),
    ("SoundPlayer",72,False),
    ("fpsbuf",64,False),
    ("game_joy_key",16,False),
    ("mui_Effect0",36,False),
    ("mui_Effect1",36,False),
    ("mui_MenuMusic",36,False),
    ("spi_id",3,False),
]
# Scalar globals: (name, c_type, size)
SCALARS = [
    ("frame_time_last","unsigned long long",8),
    ("progress_stepcount","unsigned long long",8),
    ("RF_joy_key","unsigned long long",8),
    ("inTimeVal","unsigned long long",8),
    ("outTimeVal","unsigned long long",8),
    ("TimeCountReg","unsigned int",4),
]

def fields_for(name):
    acc=set()
    for f in glob.glob('src/proprietary/**/*.c',recursive=True):
        t=open(f,encoding='utf-8',errors='replace').read()
        for m in re.finditer(re.escape(name)+r'\._(\d+)_([124])_',t):
            acc.add((int(m.group(1)),int(m.group(2))))
    return sorted(acc)

def emit(name,size,kind,dyn=False):
    lines=[]
    lines.append(f'typedef union {{')
    # member-field ladder
    if kind=='blob':
        lines.append(f'    struct {{');
        acc=fields_for(name)
        # group into union ladders per 4-byte window
        i=0
        # simpler: emit each accessed field individually as anonymous union? 
        # But C forbids same-name member collision across distinct fields.
        # Use the proven pattern: consecutive 4-byte windows with _N_1_ bytes + _N_4_.
        # We only need fields actually accessed; generate ladders covering them.
        # Build a set of needed (offset,width).
        needed=sorted(acc)
        # emit anonymous struct with each accessed byte field and dword field
        # To avoid name collisions, emit per-window unions exactly like gh_blob_t.
        windows=sorted(set(o for o,w in needed))
        # group contiguous multiples of 4
        cur=[]
        def flush(w):
            byte_names=[]
            d=0
            # a window at offset base covers base..base+3 if needed
            for o in range(w,w+4):
                if any(o==oo and ww==1 for oo,ww in needed):
                    byte_names.append(f'_{o}_1_')
            has4=any(o==w and ww==4 for o,ww in needed)
            has2=any(o==w and ww==2 for o,ww in needed)
            # only emit if any field in this 4-byte span is needed
            if byte_names or has4 or has2:
                parts=[]
                if byte_names:
                    parts.append('struct { '+','.join(x+',' for x in byte_names)+' };')
                if has2:
                    parts.append(f'short _{w}_2_;')
                if has4:
                    parts.append(f'unsigned int _{w}_4_;')
                lines.append(f'        union {{'+ ' '.join(parts)+' };')
        # emit 4-byte windows
        b=0
        while b+1 < size:
            flush(b)
            b+=4
        if dyn:
            # final trailing byte window for any <4-aligned byte fields
            # (windows above already cover 4-aligned spans; byte-only fields at any offset
            #  are covered since we stepped by 4 from 0; but byte fields not aligned to a
            #  4-block start are still covered because byte_names uses absolute offset)
            lines.append(f'        struct {{ unsigned char _{size-1}_1_; }};')
        lines.append(f'    }};')
        lines.append(f'    struct {{ {kind}; }};')
    else:
        lines.append(f'    {kind};')
    lines.append(f'}} {name}_blob_t;')
    return '\n'.join(lines)

out=[]
for name,size,dyn in ARRAYS:
    out.append(emit(name,size,'blob',dyn))
for name,typ,size in SCALARS:
    out.append(emit(name,size,typ))

block='\n\n'.join(out)
# insert into a generated header file
open('src/compat/named_blobs.h','w',encoding='utf-8').write(
    '/* named_blobs.h — GENERATED by tools/gen_named_blob_structs.py\n'
    ' * 为 19 个以 _N_M_ 成员访问的名义全局生成精确尺寸 blob 联合体。\n'
    ' * 偏移/宽度证据来自 src/proprietary/**/*.c 实际访问，非猜测。 */\n'
    '#ifndef RK_NAMED_BLOBS_H\n#define RK_NAMED_BLOBS_H\n#include "ghidra_compat.h"\n\n'
    +block+'\n#endif\n')
print('written src/compat/named_blobs.h with',len(ARRAYS)+len(SCALARS),'types')
print('char count', len(block))
