/* ============================================================
 * shoucang.c — 全局收藏管理器
 * ============================================================ */

#include "shoucang.h"
#include "rkgame.h"
#include "debug.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

shoucang_entry_t g_shoucang[SHOUCANG_MAX];
int g_shoucang_count = 0;

int shoucang_init(void)
{
    shoucang_clear();
    return 0;
}

void shoucang_clear(void)
{
    memset(g_shoucang, 0, sizeof(g_shoucang));
    g_shoucang_count = 0;
}

/* 原厂入口 shoucang() — 初始化 + 尝试加载 */
void shoucang(void)
{
    shoucang_init();
}

int shoucang_contains(const char *path)
{
    if (!path) return 0;
    for (int i = 0; i < g_shoucang_count; i++) {
        if (strcmp(g_shoucang[i].path, path) == 0) return 1;
    }
    return 0;
}

int shoucang_add(const char *name, const char *path, const char *type)
{
    if (!name || !path || g_shoucang_count >= SHOUCANG_MAX) return -1;
    if (shoucang_contains(path)) return g_shoucang_count - 1;
    strncpy(g_shoucang[g_shoucang_count].name, name, SHOUCANG_NAME_LEN - 1);
    strncpy(g_shoucang[g_shoucang_count].path, path, SHOUCANG_PATH_LEN - 1);
    if (type)
        strncpy(g_shoucang[g_shoucang_count].type, type, 15);
    g_shoucang[g_shoucang_count].type[15] = '\0';
    g_shoucang_count++;
    return g_shoucang_count - 1;
}

int shoucang_remove(const char *path)
{
    if (!path) return -1;
    for (int i = 0; i < g_shoucang_count; i++) {
        if (strcmp(g_shoucang[i].path, path) == 0) {
            /* 覆盖式上移 */
            for (int j = i; j < g_shoucang_count - 1; j++)
                g_shoucang[j] = g_shoucang[j + 1];
            g_shoucang_count--;
            memset(&g_shoucang[g_shoucang_count], 0,
                   sizeof(shoucang_entry_t));
            return i;
        }
    }
    return -1;
}

int shoucang_count_items(void) { return g_shoucang_count; }

int shoucang_save(const char *path)
{
    if (!path) return -1;
    FILE *fp = fopen(path, "w");
    if (!fp) return -1;
    fprintf(fp, "# shoucang list (auto-generated by rkgame)\n");
    for (int i = 0; i < g_shoucang_count; i++) {
        fprintf(fp, "%s\t%s\t%s\n",
                g_shoucang[i].type[0] ? g_shoucang[i].type : "---",
                g_shoucang[i].name,
                g_shoucang[i].path);
    }
    fclose(fp);
    LOG("shoucang_save: %d entries -> %s", g_shoucang_count, path);
    return g_shoucang_count;
}

int shoucang_load(const char *path)
{
    if (!path) return -1;
    FILE *fp = fopen(path, "r");
    if (!fp) return 0;  /* 无文件视为空收藏 */
    shoucang_clear();
    char line[512];
    while (fgets(line, sizeof(line), fp)) {
        if (line[0] == '#' || line[0] == '\n' || line[0] == '\r') continue;
        char type[32] = "---";
        char name[SHOUCANG_NAME_LEN];
        char p[SHOUCANG_PATH_LEN];
        if (sscanf(line, "%31s\t%95s\t%255s", type, name, p) == 3) {
            if (g_shoucang_count < SHOUCANG_MAX) {
                strncpy(g_shoucang[g_shoucang_count].type, type, 15);
                strncpy(g_shoucang[g_shoucang_count].name, name, SHOUCANG_NAME_LEN - 1);
                strncpy(g_shoucang[g_shoucang_count].path, p, SHOUCANG_PATH_LEN - 1);
                g_shoucang_count++;
            }
        }
    }
    fclose(fp);
    LOG("shoucang_load: %d entries from %s", g_shoucang_count, path);
    return g_shoucang_count;
}
